swagger: "2.0"
info:
  version: 1.0.0
  title: Proxy API
  description: Mobile and web proxy API gateway.
host: localhost
basePath: /api/v1
schemes:
  - https
security:
  - Token: []
paths:
  "/idp-metadata-update":
    x-swagger-router-controller: IdpMetadataController
    get:
      operationId: refresh
      summary: Update IDP Metadata
      description: |-
        Fetch IDP Metadata from remote url and update SPID Strategy
      responses:
        "200":
          description: Success.
          schema:
            $ref: "#/definitions/SuccessResponse"
          examples:
            application/json:
              "message": "IDPs Metadata Updated"
        "401":
          description: Token null or invalid.
definitions:
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
responses: {}
parameters: {}
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Token:
    type: apiKey
    name: token
    in: query
