swagger: "2.0"
info:
  version: 1.0.0
  title: Proxy API
  description: Mobile and web proxy API gateway.
host: localhost
basePath: /api/v1
schemes:
  - https
paths:
  "/services/{service_id}":
    x-swagger-router-controller: ServicesController
    parameters:
    - name: service_id
      in: path
      type: string
      required: true
      description: The ID of an existing Service.
    get:
      operationId: getService
      summary: Get Service
      description: A previously created service with the provided service ID is returned.
      responses:
        '200':
          description: Service found.
          schema:
            "$ref": "#/definitions/ServicePublic"
          examples:
            application/json:
              department_name: dept
              organization_name: org
              service_id: 2b3e728c1a5d1efa035c
              service_name: service
              version: 1
        '404':
          description: No service found for the provided ID.
      parameters: []
  "/messages":
    x-swagger-router-controller: MessagesController
    parameters:
      - $ref: "#/parameters/PaginationRequest"
    get:
      operationId: getUserMessages
      summary: Get user's messages
      description: |-
        Returns the messages for the user identified by the provided fiscal code.
        Messages will be returned in inverse acceptance order (from last to first).
        The "next" field, when present, contains an URL pointing to the next page of results.
      responses:
        "200":
          description: Found.
          schema:
            allOf:
              - type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/definitions/Message"
              - $ref: "#/definitions/PaginationResponse"
          examples:
            application/json:
              items:
              - id: 01BX9NSMKVXXS5PSP2FATZMYYY
                content:
                  subject: amet sunt dolor nulla esseesseanim
                  markdown: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et mollis felis.
                    Vivamus orci nisl, commodo ut sodales ut, eleifend a libero. Donec dapibus, turpis in mattis tempor,
                    risus nunc malesuada ex, non aliquet metus nunc a lacus. Aenean in arcu vitae nisl porta
                    fermentum nec non nibh. Phasellus tortor tellus, semper in metus eget, eleifend
                    laoreet nibh. Aenean feugiat lectus ut nisl eleifend gravida.
              - id: 01BX9NSMKVXXS5PSP2FATZM123
                content:
                  subject: idUt quis tempor esseesseanim
                  markdown: Nullam dapibus metus sed elementum efficitur. Curabitur facilisis sagittis risus nec sodales.
                    Vestibulum in eros sapien. Donec ac odio sit amet dui semper ornare eget nec odio. Pellentesque habitant
                    morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent nibh ex, mattis sit amet
                    felis id, sodales euismod velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              page_size: 2
              next: https://example.com/next
        "404":
          description: No message found.
        "500":
          description: There was an error in retrieving the messages.
  "/messages/{id}":
    x-swagger-router-controller: MessagesController
    parameters:
      - name: id
        in: path
        type: string
        required: true
        description: The ID of the message.
    get:
      operationId: getUserMessage
      summary: Get message
      description: |-
        Returns the message with the provided message ID.
      responses:
        "200":
          description: Found.
          schema:
            $ref: "#/definitions/Message"
          examples:
            application/json:
              message:
                id: 01BX9NSMKAAAS5PSP2FATZM6BQ
                content:
                  subject: message subject, aliquip sint nulla in estinut
                  markdown: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et mollis felis.
                    Vivamus orci nisl, commodo ut sodales ut, eleifend a libero. Donec dapibus, turpis in mattis tempor,
                    risus nunc malesuada ex, non aliquet metus nunc a lacus. Aenean in arcu vitae nisl porta
                    fermentum nec non nibh. Phasellus tortor tellus, semper in metus eget, eleifend
                    laoreet nibh. Aenean feugiat lectus ut nisl eleifend gravida.
        "404":
          description: No message found for the provided ID.
        "500":
          description: There was an error in retrieving the message.
  "/profile":
    x-swagger-router-controller: ProfileController
    get:
      operationId: getUserProfile
      summary: Get user's profile
      description: Returns the profile for the user identified by the provided fiscal code.
      responses:
        "200":
          description: Found.
          schema:
            $ref: "#/definitions/Profile"
          examples:
            application/json:
              fiscal_code: "TMMEXQ60A10Y526X"
              email: "email@example.com"
        "500":
          description: There was an error in retrieving the user profile.
    post:
      operationId: upsertProfile
      summary: Set User's profile
      description: Create or update the profile for the user identified by the provided fiscal code.
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/ExtendedProfile"
          x-examples:
            application/json:
              email: foobar@example.com
      responses:
        '200':
          description: Profile updated.
          schema:
            allOf:
            - $ref: "#/definitions/LimitedProfile"
            - $ref: "#/definitions/ExtendedProfile"
          examples:
            application/json:
              email: foobar@example.com
              version: 0
        "404":
          description: No user found for the provided fiscal code.
        '400':
          description: Invalid payload.
        '500':
          description: Profile cannot be updated.
  "/api/v1/notify":
    x-swagger-router-controller: NotificationController
    parameters:
      - in: body
        name: body
        schema:
          $ref: "#/definitions/Notification"
        x-examples:
          application/json:
            subject: "TMMEXQ60A10Y526X"
            message: "..."
    post:
      operationId: notify
      summary: Notify a user
      description: |-
        Post the notification to the user using a push notification.
      responses:
        "200":
          description: Success.
        "500":
          description: There was an error in forwarding the notification to the Notification Hub.
definitions:
  MessageContent:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#MessageContent"
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#FiscalCode"
  EmailAddress:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#EmailAddress"
  ExtendedProfile:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#ExtendedProfile"
  LimitedProfile:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#LimitedProfile"
  PreferredLanguages:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#PreferredLanguages"
  IsInboxEnabled:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#IsInboxEnabled"
  IsWebhookEnabled:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#IsWebhookEnabled"
  PaginationResponse:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/v0.38.0/api/definitions.yaml#PaginationResponse"
  Message:
    title: Message
    type: object
    properties:
      id:
        type: string
      content:
        $ref: '#/definitions/MessageContent'
      sender_service_id:
        type: string
    required:
      - id
      - content
  Profile:
    title: Profile
    description: Describes the user's profile.
    type: object
    properties:
      email:
        $ref: '#/definitions/EmailAddress'
      family_name:
        type: string
      fiscal_code:
        $ref: '#/definitions/FiscalCode'
      has_profile:
        type: boolean
      is_email_set:
        type: boolean
      is_inbox_enabled:
        $ref: "#/definitions/IsInboxEnabled"
      is_webhook_enabled:
        $ref: "#/definitions/IsWebhookEnabled"
      name:
        type: string
      preferred_email:
        $ref: '#/definitions/EmailAddress'
      preferred_languages:
        $ref: '#/definitions/PreferredLanguages'
      version:
        type: integer
    required:
      - fiscal_code
      - family_name
      - has_profile
      - is_email_set
      - name
      - version
responses: {}
parameters:
  PaginationRequest:
    name: cursor
    in: query
    type: string
    minimum: 1
    description: An opaque identifier that points to the next item in the collection.
consumes:
  - application/json
produces:
  - application/json
