swagger: "2.0"
info:
  version: 1.0.0
  title: Proxy API
  description: Mobile and web proxy API gateway.
host: localhost
basePath: /api/v1
schemes:
  - https
paths:
  "/services/{service_id}":
    x-swagger-router-controller: ServicesController
    parameters:
      - name: service_id
        in: path
        type: string
        required: true
        description: The ID of an existing Service.
    get:
      operationId: getService
      summary: Get Service
      description: A previously created service with the provided service ID is returned.
      responses:
        '200':
          description: Service found.
          schema:
            "$ref": "#/definitions/ServicePublic"
          examples:
            application/json:
              department_name: dept
              organization_name: org
              service_id: 2b3e728c1a5d1efa035c
              service_name: service
              version: 1
        '404':
          description: No service found for the provided ID.
      parameters: []
  "/messages":
    x-swagger-router-controller: MessagesController
    parameters:
      - $ref: "#/parameters/PaginationRequest"
    get:
      operationId: getUserMessages
      summary: Get user's messages
      description: |-
        Returns the messages for the user identified by the provided fiscal code.
        Messages will be returned in inverse acceptance order (from last to first).
        The "next" field, when present, contains an URL pointing to the next page of results.
      responses:
        "200":
          description: Found.
          schema:
            - $ref: "#/definitions/Messages"
          examples:
            application/json:
              items:
                - id: 01BX9NSMKVXXS5PSP2FATZMYYY
                  sender_service_id: "5a25abf4fcc89605c082f042c49a"
                - id: 01BX9NSMKVXXS5PSP2FATZM123
                  sender_service_id: "5a25abf4fcc89605c082f042c49a"
              page_size: 2
              next: https://example.com/next
        "404":
          description: No message found.
        "500":
          description: There was an error in retrieving the messages.
  "/messages/{id}":
    x-swagger-router-controller: MessagesController
    parameters:
      - name: id
        in: path
        type: string
        required: true
        description: The ID of the message.
    get:
      operationId: getUserMessage
      summary: Get message
      description: |-
        Returns the message with the provided message ID.
      responses:
        "200":
          description: Found.
          schema:
            $ref: "#/definitions/MessageWithContent"
          examples:
            application/json:
              id: 01BX9NSMKAAAS5PSP2FATZM6BQ
              subject: message subject, aliquip sint nulla in estinut
              markdown: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et mollis felis.
                Vivamus orci nisl, commodo ut sodales ut, eleifend a libero. Donec dapibus, turpis in mattis tempor,
                risus nunc malesuada ex, non aliquet metus nunc a lacus. Aenean in arcu vitae nisl porta
                fermentum nec non nibh. Phasellus tortor tellus, semper in metus eget, eleifend
                laoreet nibh. Aenean feugiat lectus ut nisl eleifend gravida.
              sender_service_id: "5a25abf4fcc89605c082f042c49a"
        "404":
          description: No message found for the provided ID.
        "500":
          description: There was an error in retrieving the message.
  "/profile":
    x-swagger-router-controller: ProfileController
    get:
      operationId: getUserProfile
      summary: Get user's profile
      description: Returns the profile for the user identified by the provided fiscal code.
      responses:
        "200":
          description: Found.
          schema:
            oneOf:
              - $ref: "#/definitions/ProfileWithEmail"
              - $ref: "#/definitions/ProfileWithoutEmail"
          examples:
            application/json:
              family_name: "Rossi"
              fiscal_code: "TMMEXQ60A10Y526X"
              has_profile: true
              is_email_set: false
              is_inbox_enabled: true
              is_webhook_enabled: false
              name: "Mario"
              preferred_email: "preferred@example.com"
              version: 1
              email: "email@example.com"
        "500":
          description: There was an error in retrieving the user profile.
    post:
      operationId: upsertProfile
      summary: Set User's profile
      description: Create or update the profile for the user identified by the provided fiscal code.
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/ExtendedProfile"
          x-examples:
            application/json:
              email: foobar@example.com
              preferred_languages: [ it_IT ]
              is_inbox_enabled: true
              is_webhook_enabled: false
              version: 1
      responses:
        '200':
          description: Profile updated.
          schema:
            allOf:
              - $ref: "#/definitions/LimitedProfile"
              - $ref: "#/definitions/ExtendedProfile"
          examples:
            application/json:
              email: foobar@example.com
              preferred_languages: [ it_IT ]
              is_inbox_enabled: true
              is_webhook_enabled: false
              version: 1
        "404":
          description: No user found for the provided fiscal code.
        '400':
          description: Invalid payload.
        '500':
          description: Profile cannot be updated.
  "/notify":
    x-swagger-router-controller: NotificationController
    post:
      operationId: notify
      summary: Notify a user
      description: |-
        Post the notification to the user using a push notification.
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Notification"
          x-examples:
            application/json:
              message:
                content:
                    subject: message subject, aliquip sint nulla in estinut
                    markdown: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et mollis felis.
                      Vivamus orci nisl, commodo ut sodales ut, eleifend a libero. Donec dapibus, turpis in mattis tempor,
                      risus nunc malesuada ex, non aliquet metus nunc a lacus. Aenean in arcu vitae nisl porta
                      fermentum nec non nibh. Phasellus tortor tellus, semper in metus eget, eleifend
                      laoreet nibh. Aenean feugiat lectus ut nisl eleifend gravida.
                created_at: "2018-05-03T16:21:38.167Z"
                fiscal_code: "TMMEXQ60A10Y526X"
                id: "01CCKCY7QQ7WCHWTH8NB504386"
                sender_service_id: "5a25abf4fcc89605c082f042c49a"
              senderMetadata:
                department_name: "Department name"
                organization_name: "Organization name"
                service_name: "Service name"
      responses:
        "200":
          description: Success.
        "500":
          description: There was an error in forwarding the notification to the Notification Hub.
  "/installations/{installationID}":
    x-swagger-router-controller: NotificationController
    parameters:
      - name: installationID
        in: path
        required: true
        description: The ID of the message.
        schema:
          $ref: "#/definitions/InstallationID"
    put:
      operationId: createOrUpdateInstallation
      summary: Create or update an Installation
      description: Create or update an Installation to the Azure Notification hub.
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Installation"
          x-examples:
            application/json:
              platform: "gcm"
              pushChannel: "fLKP3EATnBI:APA91bEy4go681jeSEpLkNqhtIrdPnEKu6Dfi-STtUiEnQn8RwMfBiPGYaqdWrmzJyXIh5Yms4017MYRS9O1LGPZwA4sOLCNIoKl4Fwg7cSeOkliAAtlQ0rVg71Kr5QmQiLlDJyxcq3p"
      responses:
        "200":
          description: Success.
        "500":
          description: There was an error in registering the device to the Notification Hub.
definitions:
  MessageContent:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/MessageContent"
  MessageSubject:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/MessageSubject"
  MessageBodyMarkdown:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/MessageBodyMarkdown"
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/FiscalCode"
  EmailAddress:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/EmailAddress"
  ExtendedProfile:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/ExtendedProfile"
  LimitedProfile:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/LimitedProfile"
  PreferredLanguages:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/PreferredLanguages"
  PreferredLanguage:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/PreferredLanguage"
  IsInboxEnabled:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/IsInboxEnabled"
  IsWebhookEnabled:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/IsWebhookEnabled"
  PaginationResponse:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/PaginationResponse"
  CreatedMessageWithContent:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/CreatedMessageWithContent"
  ServicePublic:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/ServicePublic"
  SenderMetadata:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/SenderMetadata"
  DepartmentName:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/DepartmentName"
  OrganizationName:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/OrganizationName"
  ServiceName:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/ServiceName"
  MessageResponseNotificationStatus:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/MessageResponseNotificationStatus"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/teamdigitale/digital-citizenship-functions/master/api/definitions.yaml#/ProblemJson"
  MessageWithContent:
    title: Message with content
    type: object
    properties:
      id:
        type: string
      subject:
        $ref: "#/definitions/MessageSubject"
      markdown:
        $ref: "#/definitions/MessageBodyMarkdown"
      sender_service_id:
        type: string
    required:
      - id
      - content
  MessageWithoutContent:
    title: Message without content
    type: object
    properties:
      id:
        type: string
      sender_service_id:
        type: string
    required:
      - id
      - sender_service_id
  Messages:
    title: A list of messages
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/MessageWithoutContent"
      page_size:
        $ref: '#/definitions/PageSize'
      next:
        type: string
    required:
      - items
      - page_size
  Installation:
    title: Installation
    description: Describes an app installation.
    type: object
    properties:
      platform:
        $ref: '#/definitions/Platform'
      pushChannel:
        $ref: '#/definitions/PushChannel'
    required:
      - platform
      - pushChannel
  Notification:
    title: Notification
    description: A received Notification.
    type: object
    properties:
      message:
        $ref: '#/definitions/CreatedMessageWithContent'
      senderMetadata:
        $ref: '#/definitions/SenderMetadata'
    required:
      - message
      - senderMetadata
  ProfileWithEmail:
    title: Profile with wmail
    description: Describes the user's profile.
    type: object
    properties:
      email:
        $ref: '#/definitions/EmailAddress'
      family_name:
        type: string
      fiscal_code:
        $ref: '#/definitions/FiscalCode'
      has_profile:
        $ref: "#/definitions/HasProfile"
      is_email_set:
        $ref: "#/definitions/IsEmailSet"
      is_inbox_enabled:
        $ref: "#/definitions/IsInboxEnabled"
      is_webhook_enabled:
        $ref: "#/definitions/IsWebhookEnabled"
      name:
        type: string
      preferred_email:
        $ref: '#/definitions/EmailAddress'
      preferred_languages:
        type: array
        items:
          $ref: '#/definitions/PreferredLanguage'
      version:
        $ref: '#/definitions/Version'
    required:
      - family_name
      - fiscal_code
      - has_profile
      - is_email_set
      - is_inbox_enabled
      - is_webhook_enabled
      - name
      - preferred_email
      - version
  ProfileWithoutEmail:
    title: Profile without email
    description: Describes the user's profile.
    type: object
    properties:
      family_name:
        type: string
      fiscal_code:
        $ref: '#/definitions/FiscalCode'
      has_profile:
        $ref: "#/definitions/HasProfile"
      is_email_set:
        $ref: "#/definitions/IsEmailSet"
      is_inbox_enabled:
        $ref: "#/definitions/IsInboxEnabled"
      is_webhook_enabled:
        $ref: "#/definitions/IsWebhookEnabled"
      name:
        type: string
      preferred_email:
        $ref: '#/definitions/EmailAddress'
      preferred_languages:
        type: array
        items:
          $ref: '#/definitions/PreferredLanguage'
      version:
        $ref: '#/definitions/Version'
    required:
      - family_name
      - fiscal_code
      - has_profile
      - is_email_set
      - is_inbox_enabled
      - is_webhook_enabled
      - name
      - preferred_email
      - version
  InstallationID:
    type: string
    description: |-
      The sixteen octets of an Installation ID are represented as 32 hexadecimal (base 16) digits, displayed in five groups
      separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 alphanumeric characters and four
      hyphens).
      See https://en.wikipedia.org/wiki/Universally_unique_identifier
    pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  HasProfile:
    type: boolean
    default: false
    description: True if the user has a remote profile.
  IsEmailSet:
    type: boolean
    default: false
    description:  True if the user has presonalized the email.
  Version:
    type: integer
    minimum: 0
    description: The entity version.
  PageSize:
    type: integer
    minimum: 0
    description: Number of items returned for each page.
  Platform:
    description: The platform type where the installation happened.
    type: string
    x-extensible-enum:
      - apns
      - gcm
  PushChannel:
    description: |-
      The Push Notification Service handle for this Installation.
      See https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-registration-management
    type: string
responses: {}
parameters:
  PaginationRequest:
    name: cursor
    in: query
    type: string
    minimum: 1
    description: An opaque identifier that points to the next item in the collection.
consumes:
  - application/json
produces:
  - application/json
