swagger: "2.0"
info:
  version: 1.0.0
  title: Carta Giovani Nazionale API
host: localhost
basePath: /api/v1/cgn
schemes:
  - https
security:
  - Bearer: []
paths:
  "/status":
    get:
      operationId: getCgnStatus
      summary: Get the CGN status details
      description: |
        Get the CGN status details 
        by the provided fiscal code
      responses:
        "200":
          description: CGN status details.
          schema:
            $ref: "#/definitions/Card"
        "401":
          description: Bearer token null or expired.
        "403":
          description: Forbidden.
        "404":
          description: No CGN found.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/activation":
    post:
      operationId: startCgnActivation
      summary: Start a CGN activation procedure
      description: | 
        Start a new CGN activation procedure
        for the logged user calculating if the user is
        eligible to get a CGN.
      responses:
        "201":
          description: Request created.
          schema:
            $ref: "#/definitions/InstanceId"
          headers:
            Location:
              type: string
              description: |-
                Location (URL) of created request resource.
                A GET request to this URL returns the request status and details.
        "202":
          description: Processing request.
          schema:
            $ref: "#/definitions/InstanceId"
        "401":
          description: Bearer token null or expired.
        "403":
          description: |
            Cannot activate a new CGN because the user is ineligible to get the CGN.
        "409":
          description: |
            Cannot activate the user's cgn because another updateCgn request was found
            for this user or it is already active.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"
    get:
      operationId: getCgnActivation
      summary: |
        Get CGN activation process status
      description: |
        Get informations about a CGN activation process
      responses:
        "200":
            description: Cgn activation details.
            schema:
              $ref: "#/definitions/CgnActivationDetail"
        "401":
          description: Bearer token null or expired.
        "403":
          description: Forbidden.
        "404":
          description: No CGN activation process found.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"
  "/eyca/activation":
    post:
      operationId: startEycaActivation
      summary: Start an EYCA activation procedure
      description: | 
        Start a new EYCA activation procedure
        for the logged user calculating if the user is
        eligible to enable EYCA on his CGN card.
      responses:
        "201":
          description: Request created.
          schema:
            $ref: "#/definitions/InstanceId"
          headers:
            Location:
              type: string
              description: |-
                Location (URL) of created request resource.
                A GET request to this URL returns the request status and details.
        "202":
          description: Processing request.
          schema:
            $ref: "#/definitions/InstanceId"
        "401":
          description: Bearer token null or expired.
        "403":
          description: |
            Cannot activate EYCA Card because the user is ineligible to enable EYCA.
        "409":
          description: |
            Cannot activate EYCA Card because another EYCA Card activation request was found
            for this user or it is already active.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"
    get:
      operationId: getEycaActivation
      summary: |
        Get EYCA activation process' status
      description: |
        Get informations about an EYCA activation process
      responses:
        "200":
            description: Eyca Card activation details.
            schema:
              $ref: "#/definitions/EycaActivationDetail"
        "401":
          description: Wrong or missing function key.
        "403":
          description: Forbidden.
        "404":
          description: No EYCA Card activation process found.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/eyca/status":
    get:
      operationId: getEycaStatus
      summary: Get the Eyca Card status details
      description: |
        Get the Eyca Card status details
      responses:
        "200":
          description: Eyca Card status details.
          schema:
            $ref: "#/definitions/EycaCard"
        "401":
          description: Bearer token null or expired.
        "403":
          description: Forbidden.
        "404":
          description: No Eyca Card found.
        "409":
          description: Conflict.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"
  
  "/delete":
    post:
      operationId: startCgnUnsubscription
      summary: Start a CGN unsubscription procedure
      description: | 
        Start a new CGN unsubscription procedure
        for the logged user
      responses:
        "201":
          description: Request created.
          schema:
            $ref: "#/definitions/InstanceId"
          headers:
            Location:
              type: string
              description: |
                Location (URL) of created request resource
                This location actually points to a not existing api, but semantically 201
                means that the request has been taken in charge
        "202":
          description: Processing request.
          schema:
            $ref: "#/definitions/InstanceId"
        "401":
          description: Bearer token null or expired.
        "403":
          description: |
            Cannot unsubscribe because the user is ineligible to get the CGN
        "409":
          description: |
            Cannot unsubscribe the user's cgn because another updateCgn request was found
            for this user
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/otp":
    post:
      operationId: generateOtp
      summary: |
        Generate a new Otp related to a CGN
      description: |
        Generate a new Otp used to discount an online purchase
        through a valid CGN
      responses:
        "200":
            description: Otp generated.
            schema:
              $ref: "#/definitions/Otp"
        "401":
          description: Bearer token null or expired.
        "403":
          description: Forbidden.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"
definitions:
  Timestamp:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v21.0.1/openapi/definitions.yaml#/Timestamp"
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v21.0.1/openapi/definitions.yaml#/FiscalCode"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v21.0.1/openapi/definitions.yaml#/ProblemJson"
  InstanceId:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/InstanceId"
  CommonCard:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CommonCard"
  CardPending:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CardPending"
  CardPendingDelete:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CardPendingDelete"
  CardActivated:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CardActivated"
  CardRevoked:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CardRevoked"
  CardExpired:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CardExpired"
  Card:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/Card"
  CgnActivationDetail:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CgnActivationDetail"
  EycaActivationDetail:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/EycaActivationDetail"
  EycaCard:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/EycaCard"
  EycaCardActivated:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/EycaCardActivated"
  EycaCardExpired:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/EycaCardExpired"
  EycaCardRevoked:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/EycaCardRevoked"
  CcdbNumber:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/CcdbNumber"
  Otp:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/Otp"
  OtpCode:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/v2.0.0/openapi/index.yaml#/definitions/OtpCode"

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
