swagger: "2.0"
info:
  version: 1.0.0
  title: Carta Giovani Nazionale API
host: localhost
basePath: /api/v1
schemes:
  - https
security:
  - Bearer: []
paths:
  "/cgn/status":
    get:
      operationId: getCgnStatus
      summary: |
        Get the CGN status details 
        by the provided fiscal code
      responses:
        "200":
          description: CGN status details.
          schema:
            $ref: "#/definitions/CgnStatus"
        "401":
          description: Wrong or missing function key.
        "404":
          description: No CGN found.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

definitions:
  Timestamp:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v17.3.0/openapi/definitions.yaml#/Timestamp"
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v17.3.0/openapi/definitions.yaml#/FiscalCode"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v17.3.0/openapi/definitions.yaml#/ProblemJson"

  CgnPendingStatus:
    type: object
    properties:
      status:
        type: string
        x-extensible-enum:
          - PENDING
    required:
      - status
  CgnActivatedStatus:
    type: object
    properties:
      status:
        type: string
        x-extensible-enum:
          - ACTIVATED
    required:
      - status
  CgnRevokedStatus:
    type: object
    properties:
      status:
        type: string
        x-extensible-enum:
          - REVOKED
    required:
      - status
  CgnCanceledStatus:
    type: object
    properties:
      status:
        type: string
        x-extensible-enum:
          - CANCELED
    required:
      - status
  CgnStatus:
    x-one-of: true
    allOf:
      - $ref: "#/definitions/CgnPendingStatus"
      - $ref: "#/definitions/CgnActivatedStatus"
      - $ref: "#/definitions/CgnRevokedStatus"
      - $ref: "#/definitions/CgnCanceledStatus"
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
