swagger: "2.0"
info:
  version: 1.0.0
  title: IO Sign - Backend API
host: api-app.io.pagopa.it
basePath: /api/v1/sign
schemes:
  - https
security:
  - Bearer: []
paths:
  "/qtsp/clauses":
    get:
      operationId: getQtspClausesMetadata
      summary: Get the qtsp clauses
      responses:
        "200":
          description: QTSP clauses
          schema:
            $ref: "#/definitions/QtspClausesMetadataDetailView"
        "401":
          description: Bearer token null or expired.
        "502":
          description: Bad gateway.
        "504":
          description: Gateway timeout.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/qtsp/clauses/filled_document":
    post:
      operationId: createFilledDocument
      summary: Create a filled document for QTSP.
      description: |
        This endpoint returns a url that the client should poll until the resource has been created.
      parameters:
        - in: body
          name: documentToFill
          required: true
          schema:
            $ref: '#/definitions/CreateFilledDocument'
      responses:
        "201":
          description: Filled document created
          schema:
            $ref: "#/definitions/FilledDocumentDetailView"
          headers:
            Location:
              type: string
              description: |-
                Location (URL) of created request resource.
                A GET request to this URL returns the created document.
        "400":
          description: Validation error.
        "401":
          description: Bearer token null or expired.
        "404":
          description: Resource not found.
        "502":
          description: Bad gateway.
        "504":
          description: Gateway timeout.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/signatures":
    post:
      operationId: createSignature
      summary: Create a Signature from SignatureRequest
      parameters:
        - in: body
          name: signatureToCreate
          required: true
          schema:
            $ref: '#/definitions/CreateSignatureBody'
      responses:
        "200":
          description: Signature created
          schema:
            $ref: "#/definitions/SignatureDetailView"
        "400":
          description: Validation error.
          schema:
            $ref: "#/definitions/ProblemJson"
        "401":
          description: Bearer token null or expired.
          schema:
            $ref: "#/definitions/ProblemJson"
        "403":
          description: Forbidden.
          schema:
            $ref: "#/definitions/ProblemJson"
        "404":
          description: Resource not found.
          schema:
            $ref: "#/definitions/ProblemJson"
        "502":
          description: Bad gateway.
        "504":
          description: Gateway timeout.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/signature-requests/{id}":
    post:
      operationId: getSignatureRequestById
      summary: Get a Signature Request from id
      parameters:
        - in: path
          name: id
          type: string
          description: Signature request Id
          format: ulid
          required: true
      responses:
        "200":
          description: The Signature Request detail
          schema:
            $ref: "#/definitions/SignatureRequestDetailView"
        "401":
          description: Bearer token null or expired.
          schema:
            $ref: "#/definitions/ProblemJson"
        "403":
          description: Resource not found.
          schema:
            $ref: "#/definitions/ProblemJson"
        "404":
          description: Resource not found.
          schema:
            $ref: "#/definitions/ProblemJson"
        "502":
          description: Bad gateway.
        "504":
          description: Gateway timeout.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

definitions:
  Timestamp:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v21.0.1/openapi/definitions.yaml#/Timestamp"

  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v21.0.1/openapi/definitions.yaml#/ProblemJson"

  CreateFilledDocument:
    type: object
    properties:
      document_url:
        type: string
        format: url
        minLength: 1
    required:
      - document_url

  FilledDocumentDetailView:
    type: object
    properties:
      filled_document_url:
        type: string
        format: url
    required:
      - filled_document_url

  QtspClause:
      type: object
      properties:
        text:
          type: string
          minLength: 1
      required:
        - text

  QtspClausesMetadataDetailView:
    type: object
    properties:
      clauses:
        type: array
        items:
          $ref: "#/definitions/QtspClause"
        minItems: 1
        uniqueItems: true
      document_url:
        type: string
        format: url
      privacy_url:
        type: string
        format: url
      privacy_text:
        type: string
        minLength: 1
      terms_and_conditions_url:
        type: string
        format: url
      nonce:
        type: string
        format: base64
        minLength: 1
    required:
      - clauses
      - document_url
      - privacy_url
      - privacy_text
      - terms_and_conditions_url
      - nonce

  Id:
    type: string
    description: Entity Id
    minLength: 1
    example: 01ARZ3NDEKTSV4RRFFQ69G5FAV

  Clause:
    type: object
    properties:
      title:
        type: string
      type:
        type: string
        enum: ["REQUIRED", "UNFAIR", "OPTIONAL"]
    required:
      - title
      - type

  ExistingSignatureFieldAttrs:
      type: object
      properties:
        unique_name:
          type: string
          minLength: 1
      required:
        - unique_name

  SignatureFieldToBeCreatedAttrs:
    type: object
    properties:
      bottom_left:
        type: object
        properties:
          x: { type: number }
          y: { type: number }
        required:
          - x
          - y
      top_right:
        type: object
        properties:
          x: { type: number }
          y: { type: number }
        required:
          - x
          - y
      page:
        type: number
        minimum: 0
    required:
      - bottom_left
      - page
      - top_right

  SignatureFieldAttrs:
    x-one-of: true
    allOf:
      - $ref: '#/definitions/ExistingSignatureFieldAttrs'
      - $ref: '#/definitions/SignatureFieldToBeCreatedAttrs'

  SignatureField:
    type: object
    properties:
      attrs:
        $ref: "#/definitions/SignatureFieldAttrs"
      clause:
        $ref: "#/definitions/Clause"
    required:
      - attrs
      - clause

  DocumentToSign:
    type: object
    properties:
      document_id:
        type: string
        format: ulid
        minLength: 1
      signature_fields:
        type: array
        items:
          $ref: "#/definitions/SignatureField"
    required:
      - document_id
      - signature_fields

  QtspClauses:
    type: object
    properties:
      accepted_clauses:
        type: array
        items:
          $ref: "#/definitions/QtspClause"
        minItems: 1
        uniqueItems: true
      filled_document_url:
        type: string
        format: url
        minLength: 1
      nonce:
        type: string
        format: base64
        minLength: 1
    required:
      - accepted_clauses
      - filled_document_url
      - nonce

  CreateSignatureBody:
    type: object
    properties:
      signature_request_id:
        $ref: "#/definitions/Id"
      documents_to_sign:
        type: array
        items:
          $ref: "#/definitions/DocumentToSign"
        minItems: 1
        uniqueItems: true
      qtsp_clauses:
        $ref: "#/definitions/QtspClauses"
    required:
      - signature_request_id
      - documents_to_sign
      - qtsp_clauses

  SignatureDetailView:
    type: object
    properties:
      id:
        $ref: "#/definitions/Id"
      signature_request_id:
        $ref: "#/definitions/Id"
      qtsp_signature_request_id:
        $ref: "#/definitions/Id"
      status:
        type: string
        enum: ["CREATED", "READY", "WAITING", "COMPLETED", "FAILED"]
      created_at:
        $ref: "#/definitions/Timestamp"
      updated_at:
        $ref: "#/definitions/Timestamp"
    required:
      - id
      - signature_request_id
      - qtsp_signature_request_id
      - status

  DocumentMetadata:
      type: object
      properties:
        title:
          type: string
        signature_fields:
          type: array
          items:
            $ref: "#/definitions/SignatureField"
      required:
        - title
        - signature_fields

  DocumentDetailView:
      type: object
      properties:
        id:
          $ref: "#/definitions/Id"
        metadata:
          $ref: "#/definitions/DocumentMetadata"
        url:
          type: string
          format: uri
        created_at:
          $ref: "#/definitions/Timestamp"
        updated_at:
          $ref: "#/definitions/Timestamp"
      required:
        - id
        - metadata
        - url
        - created_at
        - updated_at

  SignatureRequestDetailView:
    type: object
    properties:
      id:
        $ref: "#/definitions/Id"
      status:
        type: string
        x-extensible-enum:
          - WAIT_FOR_SIGNATURE
          - WAIT_FOR_QTSP
          - SIGNED
          - REJECTED
      dossier_id:
        $ref: "#/definitions/Id"
      signer_id:
        $ref: "#/definitions/Id"
      expires_at:
        $ref: "#/definitions/Timestamp"
      documents:
        type: array
        items:
          $ref: "#/definitions/DocumentDetailView"
      created_at:
        $ref: "#/definitions/Timestamp"
      updated_at:
        $ref: "#/definitions/Timestamp"
      qr_code_url:
        type: string
        format: uri
    required:
      - id
      - status
      - dossier_id
      - signer_id
      - expires_at
      - documents
      - created_at
      - updated_at

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header