swagger: "2.0"
info:
  version: 1.0.0
  title: Proxy API
  description: Mobile and web proxy API gateway.
host: localhost
basePath: /pagopa/api/v1
schemes:
  - https
paths:
definitions:
  Platform:
    $ref: 'https://raw.githubusercontent.com/pagopa/io-backend/v5.19.1/api_backend.yaml#/definitions/Platform'
  NotificationHubMessageKind:
    type: string
    enum:
      - "NotifyKind"
      - "CreateOrUpdateKind"
      - "DeleteKind"
  NotificationHubMessage:
    type: object
    properties:
      installationId:
        type: string
        minLenght: 1
    required:
      - installationId
  NotificationHubNotifyMessagePayload:
    title: Notification payload
    description: Push notification payload
    type: object
    properties:
      message:
        type: string
      message_id:
        type: string
      title:
        type: string
    required:
      - message
      - message_id
      - title
  NotificationHubNotifyMessage:
    title: Notify message
    description: Message sent to the queue for a new notify event
    allOf:
      - $ref: "#/definitions/NotificationHubMessage"
      - type: object
        properties:
          payload:
            $ref: '#/definitions/NotificationHubNotifyMessagePayload'
          kind:
            type: string
            enum:
              - "NotifyKind"
        required:
          - payload
          - kind
  NotificationHubCreateOrUpdateMessage:
    title: CreateOrUpdate message
    description: Message sent to the queue for a new CreateOrUpdate event
    allOf:
      - $ref: "#/definitions/NotificationHubMessage"
      - type: object
        properties:
          kind:
            type: string
            enum:
              - "CreateOrUpdateKind"
          platform:
            $ref: '#/definitions/Platform'
          pushChannel:
            type: string
          tags:
            type: array
            items:
              type: string
        required:
          - platform
          - pushChannel
          - tags
          - kind
  NotificationHubDeleteMessage:
    title: Delete Installation message
    description: Message sent to the queue for a new Delete Installation event
    allOf:
      - $ref: "#/definitions/NotificationHubMessage"
      - type: object
        properties:
          kind:
            type: string
            enum:
              - DeleteKind
        required:
          - kind
responses: {}
parameters: {}
consumes:
  - application/json
produces:
  - application/json