swagger: "2.0"
info:
  version: 1.0.0
  title: Public API
  description: Mobile and web proxy API gateway.
host: localhost
basePath: /
schemes:
  - https
paths:
  "/info":
    x-swagger-router-controller: ServerInfoController
    get:
      operationId: getServerInfo
      summary: Runtime server info
      description: >
        Returns runtime information about the server.
      responses:
        "200":
          description: Runtime server info.
          schema:
            $ref: "#/definitions/ServerInfo"
          examples:
            application/json:
              version: "0.0.1"
              minAppVersion: "0.0.0"
              minAppVersionPagoPa: "0.0.0"
definitions:
  ServerInfo:
    type: object
    title: Server information
    properties:
      version:
        type: string
      minAppVersion:
        type: string
      minAppVersionPagoPa:
        type: string
    required:
      - version
      - minAppVersion
      - minAppVersionPagoPa
consumes:
  - application/json
produces:
  - application/json
