swagger: "2.0"
info:
  version: 1.0.0
  title: Carta Giovani Nazionale API
host: localhost
basePath: /api/v1
schemes:
  - https
security:
  - Bearer: []
paths:
  "/cgn/status":
    get:
      operationId: getCgnStatus
      summary: |
        Get the CGN status details 
        by the provided fiscal code
      responses:
        "200":
          description: CGN status details.
          schema:
            $ref: "#/definitions/CgnStatus"
        "401":
          description: Wrong or missing function key.
        "404":
          description: No CGN found.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

definitions:
  Timestamp:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v17.3.0/openapi/definitions.yaml#/Timestamp"
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v17.3.0/openapi/definitions.yaml#/FiscalCode"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v17.3.0/openapi/definitions.yaml#/ProblemJson"

  CgnPendingStatus:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/master/openapi/index.yaml#/definitions/CgnPendingStatus"
  CgnActivatedStatus:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/master/openapi/index.yaml#/definitions/CgnActivatedStatus"
  CgnRevokedStatus:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/master/openapi/index.yaml#/definitions/CgnRevokedStatus"
  CgnCanceledStatus:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/master/openapi/index.yaml#/definitions/CgnCanceledStatus"
  CgnStatus:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-cgn/master/openapi/index.yaml#/definitions/CgnStatus"
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
