swagger: "2.0"
info:
  version: 1.0.0
  title: Bonus vacanze API
host: localhost
basePath: /api/v1
schemes:
  - https
security:
  - Bearer: []
paths:
  "/bonus/vacanze/eligibility":
    post:
      operationId: startBonusEligibilityCheck
      summary: Start bonus eligibility check (ISEE)
      responses:
        "202":
          description: Request accepted.
          schema:
            type: object
            properties:
              id:
                type: string
                description: The identifier of the created request.
          headers:
            Location:
              type: string
              description: |-
                Location (URL) of created request resource.
                A GET request to this URL returns the request status and details.
          examples:
            application/json:
              id: SPNDNL80R11C522K
        "401":
          description: Bearer token null or expired.
        "409":
          description: "Conflict: pending request found."
          schema:
            $ref: "#/definitions/ProblemJson"
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

    get:
      operationId: getBonusEligibilityCheck
      summary: Get eligibility (ISEE) check information for user's bonus
      responses:
        "202":
          description: Processing request.
          schema:
            type: object
            properties:
              id:
                type: string
                description: The identifier of the created request.
          examples:
            application/json:
              id: SPNDNL80R11C522K
        "200":
          description: Request processed.
          schema:
            $ref: "#/definitions/EligibilityCheck"
          examples:
            application/json:
              id: SPNDNL80R11C522K
              status: ELIGIBLE
              family_members:
                - name: "Mario"
                  surname: "Rossi"
                  fiscal_code: "XXXYYY80R13C555Y"
                - name: "Piero"
                  surname: "Rossi"
                  fiscal_code: "ZZZYYY80R13C555Y"
                - name: "Giulia"
                  surname: "Rossi"
                  fiscal_code: "WWWYYY80R13C555Y"
              max_amount: 50000
              max_tax_benefit: 3000
        "401":
          description: Bearer token null or expired.
        "404":
          description: Request not found.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/bonus/vacanze/eligibility/notifications":
    delete:
      operationId: cancelBonusEligibilityProcedure
      summary: |
        Stop the bonus eligibility check procedure to avoid
        sending a push notification when done.
      responses:
        "200":
          description: Request canceled.
          schema:
            type: object
            properties:
              id:
                type: string
                description: The identifier of the canceled request.
          examples:
            application/json:
              id: SPNDNL80R11C522K
        "401":
          description: Bearer token null or expired.
        "404":
          description: Not found.
        "409":
          description: "Conflict: pending request found."
          schema:
            $ref: "#/definitions/ProblemJson"
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  ## BONUS ACTIVATIONS

  "/bonus/vacanze/activations":
    post:
      operationId: startBonusActivationProcedure
      summary: Start bonus activation request procedure
      responses:
        "202":
          description: Request accepted.
          schema:
            type: object
            properties:
              id:
                type: string
                description: The identifier of the created request.
          headers:
            Location:
              type: string
              description: |-
                Location (URL) of created activation resource.
                A GET request to this URL returns the request status and details.
          examples:
            application/json:
              id: SOMEBONUSID
        "409":
          description: |
            Cannot activate a new bonus because another bonus related to this user was found.
        "403":
          description: |
            Cannot activate a new bonus because the eligibility data has expired.
            The user must re-initiate the eligibility procedure to refresh her data
            and retry to activate the bonus within 24h since her got the result.
        "401":
          description: Bearer token null or expired.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

    get:
      operationId: getAllBonusActivations
      summary: |
        Get all IDs of the bonus activations requested by
        the authenticated user or by any between his family member
      responses:
        "200":
          description: |
            List of bonus activations ID activated or consumed by the authenticated user 
            or by any between his family members (former and actual)
          schema:
            $ref: "#/definitions/PaginatedBonusActivationsCollection"
        "404":
          description: No activation found.
        "401":
          description: Bearer token null or expired.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

  "/bonus/vacanze/activations/{bonus_id}":
    get:
      operationId: getLatestBonusActivationById
      summary: |
        Get the activation details for the latest version
        of the bonus entity identified by the provided id
      parameters:
        - name: bonus_id
          in: path
          required: true
          description: Bonus activation ID.
          type: string
      responses:
        "202":
          description: Processing request.
          schema:
            type: object
            properties:
              id:
                type: string
                description: The identifier of the created request.
          examples:
            application/json:
              id: SOMEBONUSID
        "200":
          description: Bonus activation details.
          schema:
            $ref: "#/definitions/BonusActivation"
          examples:
            application/json:
              id: SOMEBONUSID
              applicant_fiscal_code: SPNDNL80R11C522K
              code: MYSECRETCODE
              qr_code:
                mime_type: "svg+xml"
                base64_content: "foobar"
              max_amount: 50000
              max_tax_benefit: 3000
              updated_at: "2020-07-04T12:20:00.000Z"
              status: ACTIVE
        "401":
          description: Bearer token null or expired.
        "404":
          description: No bonus found.
        "500":
          description: Service unavailable.
          schema:
            $ref: "#/definitions/ProblemJson"

definitions:
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v10.2.3/openapi/definitions.yaml#/FiscalCode"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v10.2.3/openapi/definitions.yaml#/ProblemJson"
  EligibilityCheckStatus:
    type: string
    description: |
      Eligibility check status.
      - USER_NOT_FOUND    User not found in INPS database
      - ISEE_NOT_FOUND    User found but there's no ISEE data
      - ELIGIBILE         The user is eligible for the bonus
      - INELIGIBLE        The user is not eligible for the bonus
    x-extensible-enum:
      - USER_NOT_FOUND
      - ISEE_NOT_FOUND
      - ELIGIBILE
      - INELIGIBLE
  FamilyMember:
    type: object
    properties:
      fiscal_code:
        $ref: '#/definitions/FiscalCode'
      name:
        type: string
        minLength: 1
      surname:
        type: string
        minLength: 1
    required:
      - name
      - surname
  EligibilityCheck:
    type: object
    title: Eligibility check
    description: Eligibility check
    properties:
      id:
        type: string
        minLength: 1
      status:
        $ref: "#/definitions/EligibilityCheckStatus"
      family_members:
        type: array
        items:
          $ref: "#/definitions/FamilyMember"
      max_amount:
        description: Max bonus amount in euro cents
        type: integer
        minimum: 0
        maximum: 50000
      max_tax_benefit:
        description: Max bonus tax benefit in euro cents
        type: integer
        minimum: 0
        maximum: 50000
    required:
      - id
      - status
      - max_amount
      - tax_benefit
      - family_members
  QrCodeImage:
    type: object
    properties:
      content:
        type: string
      mime_type:
        type: string
    required:
      - content
      - mime_type
  QrCode:
    type: array
    items:
        $ref: '#/definitions/QrCodeImage'
  BonusActivationStatus:
    type: string
    description: |
      Bonus activation status.
      - ACTIVE      The bonus has been successfully activated by this user
      - VOIDED      The bonus activation was cancelled on purpose and can be resumed
      - FAILED      The bonus activation failed as the user is currently ineligible
      - CONSUMED    The bonus is comsumed by this user or any member of the family
                    and cannot be activated anymore
    x-extensible-enum:
      - ACTIVE
      - VOIDED
      - FAILED
      - CONSUMED
  BonusActivation:
    type: object
    title: Bonus activation
    description: Bonus activation
    properties:
      id:
        type: string
        minLength: 1
      applicant_fiscal_code:
        $ref: '#/definitions/FiscalCode'
      status:
        $ref: "#/definitions/BonusActivationStatus"
      code:
        type: string
        minLength: 1
      qr_code:
        $ref: "#/definitions/QrCode"
      max_amount:
        description: Max bonus amount in euro cents
        type: integer
        minimum: 0
        maximum: 50000
      max_tax_benefit:
        description: Max bonus tax benefit in euro cents
        type: integer
        minimum: 0
        maximum: 50000
      updated_at:
        $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/master/openapi/definitions.yaml#/Timestamp"
    required:
      - id
      - applicant_fiscal_code
      - status
      - code
      - qr_code
      - max_amount
      - max_tax_benefit
      - updated_at

  BonusActivationItem:
    type: object
    properties:
      id:
        type: string
        minLength: 1
      is_applicant:
        type: boolean
    required:
      - id
      - is_applicant
  BonusActivationCollection:
    items:
      type: array
      items:
        $ref: "#/definitions/BonusActivationItem"
    required:
      - items
  PaginatedBonusActivationsCollection:
    allOf: 
      - $ref: "#/definitions/BonusActivationCollection"
      - $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v10.2.3/openapi/definitions.yaml#/PaginationResponse"            
