swagger: "2.0"
info:
  version: 1.0.0
  title: Proxy API
  description: Collection of enpoints to interact with user session.
host: localhost
basePath: /api/v1
schemes:
  - https
security:
  - Token: []
paths:
  "/session/:fiscal_code/lock"
    post:
      operationId: lockUserSession
      summary: Lock a user session and delete session data
      description: |-
        Use this operation if you want to block a user to log in. The operation succeed if the user is already blocked
      parameters:
        - in: path
          name: fiscal_code
          required: true
          schema:
            $ref: '#/definitions/FiscalCode'
      responses:
        "200":
          description: Success.
          schema:
            $ref: "#/definitions/SuccessResponse"
          examples:
            application/json:
              "message": "ok"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/ProblemJson"
        "401":
          description: Token null or invalid.
        "404":
          description: User not found.
        "500":
          description: There was an error
          schema:
            $ref: "#/definitions/ProblemJson"
    delete:
      operationId: unlockUserSession
      summary: Remove a lock to a user session
      description: |-
        Use this operation if you want to unblock a user and re-allow to login. The operation succeed if the user wasn't blocked
      parameters:
        - in: path
          name: fiscal_code
          required: true
          schema:
            $ref: '#/definitions/FiscalCode'
      responses:
        "200":
          description: Success.
          schema:
            $ref: "#/definitions/SuccessResponse"
          examples:
            application/json:
              "message": "ok"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/ProblemJson"
        "401":
          description: Token null or invalid.
        "500":
          description: There was an error
          schema:
            $ref: "#/definitions/ProblemJson"
definitions:
  FiscalCode:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v5.0.0/openapi/definitions.yaml#/FiscalCode"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v5.0.0/openapi/definitions.yaml#/ProblemJson"
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
responses: {}
parameters: {}
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Token:
    type: apiKey
    name: token
    in: query
