// flow-typed signature: c2b25dba44802701ae2adb5b2911a2d5
// flow-typed version: <<STUB>>/babel-preset-es2015-node5_v*/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-node5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-node5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-es2015-node5/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-es2015-node5/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-node5/lib/index'>;
}
