// flow-typed signature: 1385ddf0a6be4229cd698a2b7fc43234
// flow-typed version: <<STUB>>/flow-runtime-validators_v^0.16.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-runtime-validators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-runtime-validators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-runtime-validators/config/eslint' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/flow-runtime-validators' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/flow-typed/mocha' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/__tests__/validators.test' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/color' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/common.test' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/composeValidators' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/date' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/dateTime' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/email' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/exclusiveMaximum' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/exclusiveMinimum' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/hostname' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/index' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/integer' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/ipv4' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/ipv6' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/jsonPointer' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/length' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/makeFormatValidator' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/maximum' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/maxItems' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/maxLength' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/maxProperties' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/minimum' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/minItems' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/minLength' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/minProperties' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/multipleOf' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/not' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/number' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/oneOf' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/pattern' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/patternProperties' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/regex' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/regexp' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/registerMobxTypes.test' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/time' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/uniqueItems' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/uri' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/uriref' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/uriReference' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/uriTemplate' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/Validator' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/validators/index' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/validators/length' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/validators/number' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/lib/validators/regexp' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/src/__tests__/validators.test' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/src/index' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/src/length' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/src/makeFormatValidator' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/src/number' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/src/regexp' {
  declare module.exports: any;
}

declare module 'flow-runtime-validators/test-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-runtime-validators/config/eslint.js' {
  declare module.exports: $Exports<'flow-runtime-validators/config/eslint'>;
}
declare module 'flow-runtime-validators/flow-runtime-validators.js' {
  declare module.exports: $Exports<'flow-runtime-validators/flow-runtime-validators'>;
}
declare module 'flow-runtime-validators/flow-typed/mocha.js' {
  declare module.exports: $Exports<'flow-runtime-validators/flow-typed/mocha'>;
}
declare module 'flow-runtime-validators/lib/__tests__/validators.test.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/__tests__/validators.test'>;
}
declare module 'flow-runtime-validators/lib/color.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/color'>;
}
declare module 'flow-runtime-validators/lib/common.test.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/common.test'>;
}
declare module 'flow-runtime-validators/lib/composeValidators.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/composeValidators'>;
}
declare module 'flow-runtime-validators/lib/date.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/date'>;
}
declare module 'flow-runtime-validators/lib/dateTime.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/dateTime'>;
}
declare module 'flow-runtime-validators/lib/email.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/email'>;
}
declare module 'flow-runtime-validators/lib/exclusiveMaximum.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/exclusiveMaximum'>;
}
declare module 'flow-runtime-validators/lib/exclusiveMinimum.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/exclusiveMinimum'>;
}
declare module 'flow-runtime-validators/lib/hostname.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/hostname'>;
}
declare module 'flow-runtime-validators/lib/index.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/index'>;
}
declare module 'flow-runtime-validators/lib/integer.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/integer'>;
}
declare module 'flow-runtime-validators/lib/ipv4.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/ipv4'>;
}
declare module 'flow-runtime-validators/lib/ipv6.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/ipv6'>;
}
declare module 'flow-runtime-validators/lib/jsonPointer.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/jsonPointer'>;
}
declare module 'flow-runtime-validators/lib/length.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/length'>;
}
declare module 'flow-runtime-validators/lib/makeFormatValidator.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/makeFormatValidator'>;
}
declare module 'flow-runtime-validators/lib/maximum.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/maximum'>;
}
declare module 'flow-runtime-validators/lib/maxItems.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/maxItems'>;
}
declare module 'flow-runtime-validators/lib/maxLength.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/maxLength'>;
}
declare module 'flow-runtime-validators/lib/maxProperties.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/maxProperties'>;
}
declare module 'flow-runtime-validators/lib/minimum.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/minimum'>;
}
declare module 'flow-runtime-validators/lib/minItems.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/minItems'>;
}
declare module 'flow-runtime-validators/lib/minLength.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/minLength'>;
}
declare module 'flow-runtime-validators/lib/minProperties.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/minProperties'>;
}
declare module 'flow-runtime-validators/lib/multipleOf.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/multipleOf'>;
}
declare module 'flow-runtime-validators/lib/not.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/not'>;
}
declare module 'flow-runtime-validators/lib/number.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/number'>;
}
declare module 'flow-runtime-validators/lib/oneOf.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/oneOf'>;
}
declare module 'flow-runtime-validators/lib/pattern.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/pattern'>;
}
declare module 'flow-runtime-validators/lib/patternProperties.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/patternProperties'>;
}
declare module 'flow-runtime-validators/lib/regex.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/regex'>;
}
declare module 'flow-runtime-validators/lib/regexp.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/regexp'>;
}
declare module 'flow-runtime-validators/lib/registerMobxTypes.test.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/registerMobxTypes.test'>;
}
declare module 'flow-runtime-validators/lib/time.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/time'>;
}
declare module 'flow-runtime-validators/lib/uniqueItems.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/uniqueItems'>;
}
declare module 'flow-runtime-validators/lib/uri.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/uri'>;
}
declare module 'flow-runtime-validators/lib/uriref.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/uriref'>;
}
declare module 'flow-runtime-validators/lib/uriReference.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/uriReference'>;
}
declare module 'flow-runtime-validators/lib/uriTemplate.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/uriTemplate'>;
}
declare module 'flow-runtime-validators/lib/Validator.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/Validator'>;
}
declare module 'flow-runtime-validators/lib/validators/index.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/validators/index'>;
}
declare module 'flow-runtime-validators/lib/validators/length.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/validators/length'>;
}
declare module 'flow-runtime-validators/lib/validators/number.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/validators/number'>;
}
declare module 'flow-runtime-validators/lib/validators/regexp.js' {
  declare module.exports: $Exports<'flow-runtime-validators/lib/validators/regexp'>;
}
declare module 'flow-runtime-validators/src/__tests__/validators.test.js' {
  declare module.exports: $Exports<'flow-runtime-validators/src/__tests__/validators.test'>;
}
declare module 'flow-runtime-validators/src/index.js' {
  declare module.exports: $Exports<'flow-runtime-validators/src/index'>;
}
declare module 'flow-runtime-validators/src/length.js' {
  declare module.exports: $Exports<'flow-runtime-validators/src/length'>;
}
declare module 'flow-runtime-validators/src/makeFormatValidator.js' {
  declare module.exports: $Exports<'flow-runtime-validators/src/makeFormatValidator'>;
}
declare module 'flow-runtime-validators/src/number.js' {
  declare module.exports: $Exports<'flow-runtime-validators/src/number'>;
}
declare module 'flow-runtime-validators/src/regexp.js' {
  declare module.exports: $Exports<'flow-runtime-validators/src/regexp'>;
}
declare module 'flow-runtime-validators/test-polyfill.js' {
  declare module.exports: $Exports<'flow-runtime-validators/test-polyfill'>;
}
