// flow-typed signature: d81cac6d413fa083d2bea30e50027fff
// flow-typed version: <<STUB>>/ms-rest_v^2.2.7/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ms-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ms-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ms-rest/lib/constants' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/credentials/apiKeyCredentials' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/credentials/basicAuthenticationCredentials' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/credentials/tokenCredentials' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/exponentialRetryPolicyFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/formDataFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/logFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/msRestUserAgentFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/proxyFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/redirectFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/signingFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/filters/systemErrorRetryPolicyFilter' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/httpOperationResponse' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/msRest' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/requestPipeline' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/serialization' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/serviceClient' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/utils' {
  declare module.exports: any;
}

declare module 'ms-rest/lib/webResource' {
  declare module.exports: any;
}

declare module 'ms-rest/test/credentialTests' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/cat' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/dog' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/fish' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/index' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/invoice' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/pet' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/petAP' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/petgallery' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/product' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/productListResult' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/productListResultNextLink' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/sawshark' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/shark' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/models/subProduct' {
  declare module.exports: any;
}

declare module 'ms-rest/test/data/TestClient/lib/testClient' {
  declare module.exports: any;
}

declare module 'ms-rest/test/formDataFilterTests' {
  declare module.exports: any;
}

declare module 'ms-rest/test/logFilterTests' {
  declare module.exports: any;
}

declare module 'ms-rest/test/proxyFilterTests' {
  declare module.exports: any;
}

declare module 'ms-rest/test/redirectFilterTests' {
  declare module.exports: any;
}

declare module 'ms-rest/test/retryPolicyTests' {
  declare module.exports: any;
}

declare module 'ms-rest/test/serializationTests' {
  declare module.exports: any;
}

declare module 'ms-rest/test/unit' {
  declare module.exports: any;
}

declare module 'ms-rest/test/userAgentFilterTests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ms-rest/lib/constants.js' {
  declare module.exports: $Exports<'ms-rest/lib/constants'>;
}
declare module 'ms-rest/lib/credentials/apiKeyCredentials.js' {
  declare module.exports: $Exports<'ms-rest/lib/credentials/apiKeyCredentials'>;
}
declare module 'ms-rest/lib/credentials/basicAuthenticationCredentials.js' {
  declare module.exports: $Exports<'ms-rest/lib/credentials/basicAuthenticationCredentials'>;
}
declare module 'ms-rest/lib/credentials/tokenCredentials.js' {
  declare module.exports: $Exports<'ms-rest/lib/credentials/tokenCredentials'>;
}
declare module 'ms-rest/lib/filters/exponentialRetryPolicyFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/exponentialRetryPolicyFilter'>;
}
declare module 'ms-rest/lib/filters/formDataFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/formDataFilter'>;
}
declare module 'ms-rest/lib/filters/logFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/logFilter'>;
}
declare module 'ms-rest/lib/filters/msRestUserAgentFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/msRestUserAgentFilter'>;
}
declare module 'ms-rest/lib/filters/proxyFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/proxyFilter'>;
}
declare module 'ms-rest/lib/filters/redirectFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/redirectFilter'>;
}
declare module 'ms-rest/lib/filters/signingFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/signingFilter'>;
}
declare module 'ms-rest/lib/filters/systemErrorRetryPolicyFilter.js' {
  declare module.exports: $Exports<'ms-rest/lib/filters/systemErrorRetryPolicyFilter'>;
}
declare module 'ms-rest/lib/httpOperationResponse.js' {
  declare module.exports: $Exports<'ms-rest/lib/httpOperationResponse'>;
}
declare module 'ms-rest/lib/msRest.js' {
  declare module.exports: $Exports<'ms-rest/lib/msRest'>;
}
declare module 'ms-rest/lib/requestPipeline.js' {
  declare module.exports: $Exports<'ms-rest/lib/requestPipeline'>;
}
declare module 'ms-rest/lib/serialization.js' {
  declare module.exports: $Exports<'ms-rest/lib/serialization'>;
}
declare module 'ms-rest/lib/serviceClient.js' {
  declare module.exports: $Exports<'ms-rest/lib/serviceClient'>;
}
declare module 'ms-rest/lib/utils.js' {
  declare module.exports: $Exports<'ms-rest/lib/utils'>;
}
declare module 'ms-rest/lib/webResource.js' {
  declare module.exports: $Exports<'ms-rest/lib/webResource'>;
}
declare module 'ms-rest/test/credentialTests.js' {
  declare module.exports: $Exports<'ms-rest/test/credentialTests'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/cat.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/cat'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/dog.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/dog'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/fish.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/fish'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/index.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/index'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/invoice.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/invoice'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/pet.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/pet'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/petAP.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/petAP'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/petgallery.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/petgallery'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/product.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/product'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/productListResult.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/productListResult'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/productListResultNextLink.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/productListResultNextLink'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/sawshark.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/sawshark'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/shark.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/shark'>;
}
declare module 'ms-rest/test/data/TestClient/lib/models/subProduct.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/models/subProduct'>;
}
declare module 'ms-rest/test/data/TestClient/lib/testClient.js' {
  declare module.exports: $Exports<'ms-rest/test/data/TestClient/lib/testClient'>;
}
declare module 'ms-rest/test/formDataFilterTests.js' {
  declare module.exports: $Exports<'ms-rest/test/formDataFilterTests'>;
}
declare module 'ms-rest/test/logFilterTests.js' {
  declare module.exports: $Exports<'ms-rest/test/logFilterTests'>;
}
declare module 'ms-rest/test/proxyFilterTests.js' {
  declare module.exports: $Exports<'ms-rest/test/proxyFilterTests'>;
}
declare module 'ms-rest/test/redirectFilterTests.js' {
  declare module.exports: $Exports<'ms-rest/test/redirectFilterTests'>;
}
declare module 'ms-rest/test/retryPolicyTests.js' {
  declare module.exports: $Exports<'ms-rest/test/retryPolicyTests'>;
}
declare module 'ms-rest/test/serializationTests.js' {
  declare module.exports: $Exports<'ms-rest/test/serializationTests'>;
}
declare module 'ms-rest/test/unit.js' {
  declare module.exports: $Exports<'ms-rest/test/unit'>;
}
declare module 'ms-rest/test/userAgentFilterTests.js' {
  declare module.exports: $Exports<'ms-rest/test/userAgentFilterTests'>;
}
