// flow-typed signature: f85eb9e1436a0d3dc6886b8396521a2f
// flow-typed version: <<STUB>>/passport-http-bearer_v^1.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-http-bearer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-http-bearer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-http-bearer/lib/index' {
  declare module.exports: any;
}

declare module 'passport-http-bearer/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-http-bearer/lib/index.js' {
  declare module.exports: $Exports<'passport-http-bearer/lib/index'>;
}
declare module 'passport-http-bearer/lib/strategy.js' {
  declare module.exports: $Exports<'passport-http-bearer/lib/strategy'>;
}
