// flow-typed signature: eb7afa4bab4f0a540c5695fefe42d88f
// flow-typed version: <<STUB>>/spid-passport_vgit://github.com/lussoluca/spid-passport.git#166c99b/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spid-passport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spid-passport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spid-passport/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spid-passport/example/index.js' {
  declare module.exports: $Exports<'spid-passport/example/index'>;
}
declare module 'spid-passport/index' {
  declare module.exports: $Exports<'spid-passport'>;
}
declare module 'spid-passport/index.js' {
  declare module.exports: $Exports<'spid-passport'>;
}
