swagger: '2.0'
info:
  title: Third Party Messages - Server implementation
  version: '1'
basePath: /
schemes:
  - https
paths:
  '/messages/{id}':
    get:
      operationId: getThirdPartyMessageDetails
      summary: Retrieve a Third Party message
      description: |-
        Returns the Third Party message with the provided message ID.
        User's fiscal code is required as header parameter.
      produces:
        - application/json
      parameters:
        - in: header
          name: fiscal_code
          required: true
          type: string
        - in: path
          name: id
          type: string
          minLength: 1
          required: true
          description: ID of the Third Party message.
      responses:
        '200':
          description: Found
          schema:
            $ref: '#/definitions/ThirdPartyMessageDetail'
          examples:
            text/json: |
              attachments: [], 
              custom_property: "a custom property" 
              custom_property_2: 42 
        '400':
          description: Bad Request
          schema:
            $ref: "#/definitions/ProblemJson"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: No message found for the provided ID.
          schema:
            $ref: '#/definitions/ProblemJson'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ProblemJson"
  '/messages/{id}/{attachment_url}':
    get:
      operationId: getThirdPartyMessageAttachment
      summary: Retrieve an attachment of a Third Party message
      description: |-
        Returns the Third Party message with the provided message ID.
        User's fiscal code is required as header parameter.
      produces:
        - application/octet-stream
      parameters:
        - name: id
          in: path
          type: string
          minLength: 1
          required: true
          description: ID of the IO message.
        - in: path
          name: attachment_url
          type: string
          minLength: 1
          required: true
      responses:
        '200':
          description: Success
          schema:
            type: string
            format: binary
        '400':
          description: Bad Request
          schema:
            $ref: "#/definitions/ProblemJson"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: No message found for the provided ID or no attachment found at the provided url.
          schema:
            $ref: '#/definitions/ProblemJson'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ProblemJson"
definitions:
  ThirdPartyMessageDetail:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v25.1.0/openapi/definitions.yaml#/ThirdPartyMessage"
  ProblemJson:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v25.1.0/openapi/definitions.yaml#/ProblemJson"
  