openapi: 3.0.1
info:
  title: Proxy API
  description: Mobile and web proxy API gateway.
  version: 16.12.0
servers:
- url: https://localhost/api/v1
security:
- Token: []
paths:
  /notify:
    post:
      summary: Notify a user
      description: Post the notification to the user using a push notification.
      operationId: notify
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
              example:
                message: ok
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        "401":
          description: Token null or invalid.
          content: {}
        "500":
          description: There was an error in forwarding the notification to the Notification
            Hub.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
      x-codegen-request-body-name: body
    x-swagger-router-controller: NotificationController
components:
  schemas:
    NotificationMessage:
      allOf:
      - $ref: '#/components/schemas/CreatedMessageWithContent'
      - $ref: '#/components/schemas/CreatedMessageWithoutContent'
      x-one-of: true
    Notification:
      title: Notification
      required:
      - message
      - sender_metadata
      type: object
      properties:
        message:
          $ref: '#/components/schemas/NotificationMessage'
        sender_metadata:
          $ref: '#/components/schemas/SenderMetadata'
      description: A received Notification.
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
    ServiceId:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServiceId"
    CreatedMessageWithContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/CreatedMessageWithContent"
    CreatedMessageWithoutContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/CreatedMessageWithoutContent"
    TimeToLiveSeconds:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/TimeToLiveSeconds"
    SenderMetadata:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/SenderMetadata"
    ServiceName:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ServiceName"
    OrganizationName:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/OrganizationName"
    DepartmentName:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/DepartmentName"
    Timestamp:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Timestamp"
    FiscalCode:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/FiscalCode"
    MessageContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageContent"
    NewMessageContent:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/NewMessageContent"
    MessageContentBase:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageContentBase"
    MessageSubject:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageSubject"
    MessageBodyMarkdown:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/MessageBodyMarkdown"
    PaymentNoticeNumber:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentNoticeNumber"
    PaymentAmount:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentAmount"
    PaymentData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentData"
    PaymentDataBase:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentDataBase"
    Payee:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/Payee"
    PaymentDataWithRequiredPayee:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PaymentDataWithRequiredPayee"
    PrescriptionData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/PrescriptionData"
    EUCovidCert:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/EUCovidCert"
    ThirdPartyData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ThirdPartyData"
    LegalData:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/LegalData"
    ProblemJson:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/openapi-v3-definitions/openapi/definitions_v3.yaml#/ProblemJson"
  securitySchemes:
    Token:
      type: apiKey
      name: token
      in: query
