/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a GetMessagesByUserOKResponse.
 * @extends models['PaginationResponse']
 */
class GetMessagesByUserOKResponse extends models['PaginationResponse'] {
  /**
   * Create a GetMessagesByUserOKResponse.
   * @member {array} [items]
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of GetMessagesByUserOKResponse
   *
   * @returns {object} metadata of GetMessagesByUserOKResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetMessagesByUserOKResponse',
      type: {
        name: 'Composite',
        className: 'GetMessagesByUserOKResponse',
        modelProperties: {
          pageSize: {
            required: false,
            serializedName: 'page_size',
            constraints: {
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          next: {
            required: false,
            serializedName: 'next',
            type: {
              name: 'String'
            }
          },
          items: {
            required: false,
            serializedName: 'items',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CreatedMessageElementType',
                  type: {
                    name: 'Composite',
                    className: 'CreatedMessage'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = GetMessagesByUserOKResponse;
