/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a GetProfileOKResponse.
 */
class GetProfileOKResponse {
  /**
   * Create a GetProfileOKResponse.
   * @member {array} [preferredLanguages]
   * @member {string} [email]
   * @member {number} [version]
   */
  constructor() {
  }

  /**
   * Defines the metadata of GetProfileOKResponse
   *
   * @returns {object} metadata of GetProfileOKResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetProfileOKResponse',
      type: {
        name: 'Composite',
        className: 'GetProfileOKResponse',
        modelProperties: {
          preferredLanguages: {
            required: false,
            serializedName: 'preferred_languages',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          email: {
            required: false,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          },
          version: {
            required: false,
            serializedName: 'version',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = GetProfileOKResponse;
