/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.ProblemJson = require('./problemJson');
exports.MessageContent = require('./messageContent');
exports.NewMessageDefaultAddresses = require('./newMessageDefaultAddresses');
exports.NewMessage = require('./newMessage');
exports.NotificationStatus = require('./notificationStatus');
exports.CreatedMessage = require('./createdMessage');
exports.MessageResponse = require('./messageResponse');
exports.PaginationResponse = require('./paginationResponse');
exports.LimitedProfile = require('./limitedProfile');
exports.ExtendedProfile = require('./extendedProfile');
exports.Service = require('./service');
exports.ServicePublic = require('./servicePublic');
exports.GetMessagesByUserOKResponse = require('./getMessagesByUserOKResponse');
exports.GetProfileOKResponse = require('./getProfileOKResponse');
exports.UpsertProfileOKResponse = require('./upsertProfileOKResponse');
