/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the ProblemJson class.
 * @constructor
 * @summary Problem Type
 *
 * @member {string} [type] An absolute URI that identifies the problem type.
 * When dereferenced,
 * it SHOULD provide human-readable documentation for the problem type
 * (e.g., using HTML).
 * . Default value: 'about:blank' .
 * @member {string} [title] A short, summary of the problem type. Written in
 * english and readable
 * for engineers (usually not suited for non technical stakeholders and
 * not localized); example: Service Unavailable
 * @member {number} [status]
 * @member {string} [detail] A human readable explanation specific to this
 * occurrence of the
 * problem.
 * @member {string} [instance] An absolute URI that identifies the specific
 * occurrence of the problem.
 * It may or may not yield further information if dereferenced.
 */
export interface ProblemJson {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
}

/**
 * @class
 * Initializes a new instance of the MessageContent class.
 * @constructor
 * @summary MessageContent
 *
 * @member {string} [subject]
 * @member {string} markdown
 */
export interface MessageContent {
  subject?: string;
  markdown: string;
}

/**
 * @class
 * Initializes a new instance of the NewMessageDefaultAddresses class.
 * @constructor
 * Default addresses for notifying the recipient of the message in case no
 * address for the related channel is set in his profile.
 *
 * @member {string} [email]
 */
export interface NewMessageDefaultAddresses {
  email?: string;
}

/**
 * @class
 * Initializes a new instance of the NewMessage class.
 * @constructor
 * @summary NewMessage
 *
 * @member {number} [timeToLive]
 * @member {object} content
 * @member {string} [content.subject]
 * @member {string} [content.markdown]
 * @member {object} [defaultAddresses]
 * @member {string} [defaultAddresses.email]
 */
export interface NewMessage {
  timeToLive?: number;
  content: MessageContent;
  defaultAddresses?: NewMessageDefaultAddresses;
}

/**
 * @class
 * Initializes a new instance of the NotificationStatus class.
 * @constructor
 * @summary NotificationStatus
 *
 * @member {string} [email]
 */
export interface NotificationStatus {
  email?: string;
}

/**
 * @class
 * Initializes a new instance of the CreatedMessage class.
 * @constructor
 * @summary CreatedMessage
 *
 * @member {string} [id]
 * @member {string} fiscalCode
 * @member {number} [timeToLive]
 * @member {object} [content]
 * @member {string} [content.subject]
 * @member {string} [content.markdown]
 * @member {string} senderServiceId
 */
export interface CreatedMessage {
  id?: string;
  fiscalCode: string;
  timeToLive?: number;
  content?: MessageContent;
  senderServiceId: string;
}

/**
 * @class
 * Initializes a new instance of the MessageResponse class.
 * @constructor
 * @member {object} message
 * @member {string} [message.id]
 * @member {string} [message.fiscalCode]
 * @member {number} [message.timeToLive]
 * @member {object} [message.content]
 * @member {string} [message.content.subject]
 * @member {string} [message.content.markdown]
 * @member {string} [message.senderServiceId]
 * @member {object} [notification]
 * @member {string} [notification.email]
 */
export interface MessageResponse {
  message: CreatedMessage;
  notification?: NotificationStatus;
}

/**
 * @class
 * Initializes a new instance of the PaginationResponse class.
 * @constructor
 * @summary pagination
 *
 * Pagination response parameters.
 *
 * @member {number} [pageSize] Number of items returned for each page.
 * @member {string} [next] Contains an URL to GET the next #<page_size> results
 * in the retrieved collection of items.
 */
export interface PaginationResponse {
  pageSize?: number;
  next?: string;
}

/**
 * @class
 * Initializes a new instance of the LimitedProfile class.
 * @constructor
 * @summary A citizen's profile
 *
 * Describes the citizen's profile, mostly interesting for preferences
 * attributes.
 *
 * @member {array} [preferredLanguages]
 */
export interface LimitedProfile {
  preferredLanguages?: string[];
}

/**
 * @class
 * Initializes a new instance of the ExtendedProfile class.
 * @constructor
 * @summary A citizen's profile
 *
 * Describes the citizen's profile, mostly interesting for preferences
 * attributes.
 *
 * @member {string} [email]
 * @member {array} [preferredLanguages]
 * @member {boolean} [isInboxEnabled]
 * @member {number} [version]
 */
export interface ExtendedProfile {
  email?: string;
  preferredLanguages?: string[];
  isInboxEnabled?: boolean;
  version?: number;
}

/**
 * @class
 * Initializes a new instance of the Service class.
 * @constructor
 * @summary Service
 *
 * A Service tied to an user's subscription.
 *
 * @member {string} serviceId
 * @member {string} serviceName
 * @member {string} organizationName
 * @member {string} departmentName
 * @member {array} authorizedCidrs
 * @member {array} authorizedRecipients
 * @member {number} [version]
 * @member {string} [id]
 */
export interface Service {
  serviceId: string;
  serviceName: string;
  organizationName: string;
  departmentName: string;
  authorizedCidrs: string[];
  authorizedRecipients: string[];
  version?: number;
  id?: string;
}

/**
 * @class
 * Initializes a new instance of the ServicePublic class.
 * @constructor
 * @summary Service (public)
 *
 * A Service associated to an user's subscription.
 *
 * @member {string} serviceId
 * @member {string} serviceName
 * @member {string} organizationName
 * @member {string} departmentName
 * @member {number} [version]
 */
export interface ServicePublic {
  serviceId: string;
  serviceName: string;
  organizationName: string;
  departmentName: string;
  version?: number;
}

/**
 * @class
 * Initializes a new instance of the GetMessagesByUserOKResponse class.
 * @constructor
 * @member {array} [items]
 */
export interface GetMessagesByUserOKResponse extends PaginationResponse {
  items?: CreatedMessage[];
}

/**
 * @class
 * Initializes a new instance of the GetProfileOKResponse class.
 * @constructor
 * @member {array} [preferredLanguages]
 * @member {string} [email]
 * @member {boolean} [isInboxEnabled]
 * @member {number} [version]
 */
export interface GetProfileOKResponse {
  preferredLanguages?: string[];
  email?: string;
  isInboxEnabled?: boolean;
  version?: number;
}

/**
 * @class
 * Initializes a new instance of the UpsertProfileOKResponse class.
 * @constructor
 * @member {array} [preferredLanguages]
 * @member {string} [email]
 * @member {boolean} [isInboxEnabled]
 * @member {number} [version]
 */
export interface UpsertProfileOKResponse {
  preferredLanguages?: string[];
  email?: string;
  isInboxEnabled?: boolean;
  version?: number;
}
