/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a MessageResponse.
 */
class MessageResponse {
  /**
   * Create a MessageResponse.
   * @member {object} message
   * @member {string} [message.id]
   * @member {string} [message.fiscalCode]
   * @member {number} [message.timeToLive]
   * @member {object} [message.content]
   * @member {string} [message.content.subject]
   * @member {string} [message.content.markdown]
   * @member {string} [message.senderServiceId]
   * @member {object} [notification]
   * @member {string} [notification.email]
   */
  constructor() {
  }

  /**
   * Defines the metadata of MessageResponse
   *
   * @returns {object} metadata of MessageResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MessageResponse',
      type: {
        name: 'Composite',
        className: 'MessageResponse',
        modelProperties: {
          message: {
            required: true,
            serializedName: 'message',
            type: {
              name: 'Composite',
              className: 'CreatedMessage'
            }
          },
          notification: {
            required: false,
            serializedName: 'notification',
            type: {
              name: 'Composite',
              className: 'NotificationStatus'
            }
          }
        }
      }
    };
  }
}

module.exports = MessageResponse;
