/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary Service (public)
  *
 * A Service associated to an user's subscription.
 *
 */
class ServicePublic {
  /**
   * Create a ServicePublic.
   * @member {string} serviceId
   * @member {string} serviceName
   * @member {string} organizationName
   * @member {string} departmentName
   * @member {number} [version]
   */
  constructor() {
  }

  /**
   * Defines the metadata of ServicePublic
   *
   * @returns {object} metadata of ServicePublic
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ServicePublic',
      type: {
        name: 'Composite',
        className: 'ServicePublic',
        modelProperties: {
          serviceId: {
            required: true,
            serializedName: 'service_id',
            type: {
              name: 'String'
            }
          },
          serviceName: {
            required: true,
            serializedName: 'service_name',
            type: {
              name: 'String'
            }
          },
          organizationName: {
            required: true,
            serializedName: 'organization_name',
            type: {
              name: 'String'
            }
          },
          departmentName: {
            required: true,
            serializedName: 'department_name',
            type: {
              name: 'String'
            }
          },
          version: {
            required: false,
            serializedName: 'version',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = ServicePublic;
