/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary Service
  *
 * A Service tied to an user's subscription.
 *
 */
class Service {
  /**
   * Create a Service.
   * @member {string} serviceId
   * @member {string} serviceName
   * @member {string} organizationName
   * @member {string} departmentName
   * @member {array} authorizedCidrs
   * @member {array} authorizedRecipients
   * @member {number} [version]
   * @member {string} [id]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Service
   *
   * @returns {object} metadata of Service
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Service',
      type: {
        name: 'Composite',
        className: 'Service',
        modelProperties: {
          serviceId: {
            required: true,
            serializedName: 'service_id',
            type: {
              name: 'String'
            }
          },
          serviceName: {
            required: true,
            serializedName: 'service_name',
            type: {
              name: 'String'
            }
          },
          organizationName: {
            required: true,
            serializedName: 'organization_name',
            type: {
              name: 'String'
            }
          },
          departmentName: {
            required: true,
            serializedName: 'department_name',
            type: {
              name: 'String'
            }
          },
          authorizedCidrs: {
            required: true,
            serializedName: 'authorized_cidrs',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          authorizedRecipients: {
            required: true,
            serializedName: 'authorized_recipients',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          version: {
            required: false,
            serializedName: 'version',
            type: {
              name: 'Number'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Service;
