/**
 * Do not edit this file it is auto-generated by italia-utils / gen-api-models.
 * See https://github.com/teamdigitale/italia-utils
 */
/* tslint:disable */

import * as t from "io-ts";

// required attributes
const IDPEntityDescriptorR = t.interface({
  cert: t.readonlyArray(t.string, "array of string"),

  entityID: t.string,

  entryPoint: t.string,

  logoutUrl: t.string
});

// optional attributes
const IDPEntityDescriptorO = t.partial({});

export const IDPEntityDescriptor = t.exact(
  t.intersection(
    [IDPEntityDescriptorR, IDPEntityDescriptorO],
    "IDPEntityDescriptor"
  )
);

export type IDPEntityDescriptor = t.TypeOf<typeof IDPEntityDescriptor>;
