"use strict";
/**
 *
 */
Object.defineProperty(exports, "__esModule", { value: true });
const t = require("io-ts");
const io_ts_1 = require("io-ts");
// required attributes
exports.Service = t.interface({
    departmentName: io_ts_1.string,
    organizationName: io_ts_1.string,
    serviceId: io_ts_1.string,
    serviceName: io_ts_1.string,
    version: io_ts_1.number
});
/**
 * Converts an API ServicePublic to a Proxy service.
 *
 * ServicePublic is generated by the autorest tool and is returned by and API
 * call. Here we map all properties of ServicePublic to the proxy's Service
 * model that will ensure type validation in the rest of the proxy code.
 *
 * @param from
 * @returns {Service}
 */
function ServicePublicToAppService(from) {
    return {
        departmentName: from.departmentName,
        organizationName: from.organizationName,
        serviceId: from.serviceId,
        serviceName: from.serviceName,
        version: from.version || 0
    };
}
exports.ServicePublicToAppService = ServicePublicToAppService;
//# sourceMappingURL=service.js.map