/**
 * This file contains the Service model and some functions to
 * validate and convert type to and from it.
 */

import { ServicePublic as proxyServicePublic } from "./api/ServicePublic";
import { ServicePublic as apiServicePublic } from "./api_client/servicePublic";

/**
 * Converts an API ServicePublic to a Proxy service.
 *
 * ServicePublic is generated by the autorest tool and is returned by and API
 * call. Here we map all properties of ServicePublic to the proxy's Service
 * model that will ensure type validation in the rest of the proxy code.
 */
export function toAppService(from: apiServicePublic): proxyServicePublic {
  return {
    department_name: from.departmentName,
    organization_name: from.organizationName,
    service_id: from.serviceId,
    service_name: from.serviceName,
    version: from.version
  };
}
