"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const flow_runtime_1 = require("flow-runtime");
const genericTypes_1 = require("./genericTypes");
const ServiceModel = flow_runtime_1.default.object(flow_runtime_1.default.property("serviceId", flow_runtime_1.default.string()), flow_runtime_1.default.property("serviceName", flow_runtime_1.default.string()), flow_runtime_1.default.property("organizationName", flow_runtime_1.default.string()), flow_runtime_1.default.property("departmentName", flow_runtime_1.default.string()), flow_runtime_1.default.property("version", genericTypes_1.NonNegativeNumberType));
/**
 * Converts an API ServicePublic to a Proxy service.
 *
 * ServicePublic is generated by the autorest tool and is returned by and API
 * call. Here we map all properties of ServicePublic to the proxy's Service
 * model that will ensure type validation in the rest of the proxy code.
 *
 * @param from
 * @returns {Service}
 */
function ServicePublicToAppService(from) {
    return {
        serviceId: from.serviceId,
        serviceName: from.serviceName,
        organizationName: from.organizationName,
        departmentName: from.departmentName,
        version: from.version
    };
}
exports.ServicePublicToAppService = ServicePublicToAppService;
//# sourceMappingURL=service.js.map