/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * @summary CreatedMessage
  *
 */
class CreatedMessage {
  /**
   * Create a CreatedMessage.
   * @member {string} [id]
   * @member {string} fiscalCode
   * @member {number} [timeToLive]
   * @member {object} [content]
   * @member {string} [content.subject]
   * @member {string} [content.markdown]
   * @member {string} senderServiceId
   */
  constructor() {
  }

  /**
   * Defines the metadata of CreatedMessage
   *
   * @returns {object} metadata of CreatedMessage
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CreatedMessage',
      type: {
        name: 'Composite',
        className: 'CreatedMessage',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          fiscalCode: {
            required: true,
            serializedName: 'fiscal_code',
            type: {
              name: 'String'
            }
          },
          timeToLive: {
            required: false,
            serializedName: 'time_to_live',
            type: {
              name: 'Number'
            }
          },
          content: {
            required: false,
            serializedName: 'content',
            type: {
              name: 'Composite',
              className: 'MessageContent'
            }
          },
          senderServiceId: {
            required: true,
            serializedName: 'sender_service_id',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = CreatedMessage;
