/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary Problem Type
  *
 */
class ProblemJson {
  /**
   * Create a ProblemJson.
   * @member {string} [type] An absolute URI that identifies the problem type.
   * When dereferenced,
   * it SHOULD provide human-readable documentation for the problem type
   * (e.g., using HTML).
   * . Default value: 'about:blank' .
   * @member {string} [title] A short, summary of the problem type. Written in
   * english and readable
   * for engineers (usually not suited for non technical stakeholders and
   * not localized); example: Service Unavailable
   * @member {number} [status]
   * @member {string} [detail] A human readable explanation specific to this
   * occurrence of the
   * problem.
   * @member {string} [instance] An absolute URI that identifies the specific
   * occurrence of the problem.
   * It may or may not yield further information if dereferenced.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ProblemJson
   *
   * @returns {object} metadata of ProblemJson
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ProblemJson',
      type: {
        name: 'Composite',
        className: 'ProblemJson',
        modelProperties: {
          type: {
            required: false,
            serializedName: 'type',
            defaultValue: 'about:blank',
            type: {
              name: 'String'
            }
          },
          title: {
            required: false,
            serializedName: 'title',
            type: {
              name: 'String'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'Number'
            }
          },
          detail: {
            required: false,
            serializedName: 'detail',
            type: {
              name: 'String'
            }
          },
          instance: {
            required: false,
            serializedName: 'instance',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ProblemJson;
