openapi: 3.0.1
servers:
  - url: https://io-p-weu-lollipop-fn.azurewebsites.net/api/v1/first-lollipop-consumer
info:
  title: LolliPoP Consumer Example
  description: >-
    ## Abstract
      Definition of the headers needed by the Lollipop Consumer to conclude a LolliPoP operation

    ## Diagram
      Below is a flowchart showing the headers, the ones signed by the app and those added by io-backend

                      ┌───┐                                       ┌─────┐                                    ┌──┐  
                      │APP│                                       │IO-BE│                                    │LC│  
                      └─┬─┘                                       └──┬──┘                                    └┬─┘  
        ╔═══════════════╧═════════════════╗                          │                                        │    
        ║ask user for fingerprint or pwd ░║                          │                                        │    
        ╚═══════════════╤═════════════════╝                          │                                        │    
                       ┌┴┐[01] <METHOD> /v1/custom/io-be/request/path┴┐                                       │    
                       │ │ ────────────────────────────────────────>│ │                                       │    
                       │ │                                          │ │                                       │    
                     ╔═╧═╧══════════════════════════════════════════╧═╧══╗                                    │    
                     ║x-pagopa-lollipop-original-method                 ░║                                    │    
                     ║x-pagopa-lollipop-original-url                     ║                                    │    
                     ║signature-input                                    ║                                    │    
                     ║signature                                          ║                                    │    
                     ╚═╤═╤══════════════════════════════════════════╤═╤══╝                                    │    
                       │ │                                          │ │[02] forward enriched original request┌┴┐   
                       │ │                                          │ │ ────────────────────────────────────>│ │   
                       │ │                                          │ │                                      │ │   
                       │ │                                        ╔═╧═╧══════════════════════════════════════╧═╧══╗
                       │ │                                        ║[NEW] x-pagopa-lollipop-assertion-ref         ░║
                       │ │                                        ║[NEW] x-pagopa-lollipop-assertion-type         ║
                       │ │                                        ║[NEW] x-pagopa-lollipop-user-id                ║
                       │ │                                        ║[NEW] x-pagopa-lollipop-public-key             ║
                       │ │                                        ║[NEW] x-pagopa-lollipop-auth-jwt               ║
                       │ │                                        ║x-pagopa-lollipop-original-method              ║
                       │ │                                        ║x-pagopa-lollipop-original-url                 ║
                       │ │                                        ║signature-input                                ║
                       │ │                                        ║signature                                      ║
                       │ │                                        ╚═╤═╤══════════════════════════════════════╤═╤══╝
                       │ │                                          │ │                                      │ │    
                       └┬┘                                          └┬┘                                      └┬┘
                      ┌───┐                                       ┌─────┐                                    ┌──┐  
                      │APP│                                       │IO-BE│                                    │LC│  
                      └───┘                                       └─────┘                                    └──┘  
  version: 1.0.0
security:
  - ApiKeyAuth: []

# Example endpoint
paths:
  /sign-message:
    post:
      operationId: signMessage
      summary: POST a signed request with Lollipop
      parameters:
        - name: x-pagopa-lollipop-original-method
          in: header
          description: The method of the endpoint called by IO app
          required: true
          schema:
            $ref: "#/components/schemas/LollipopMethod"
        - name: x-pagopa-lollipop-original-url
          in: header
          description: The url of the endpoint called by IO app
          required: true
          schema:
            $ref: "#/components/schemas/LollipopOriginalURL"
        - name: x-pagopa-lollipop-auth-jwt
          in: header
          description: Auth token to retrieve the SPID/CIE User identity from IO
          required: true
          schema:
            $ref: "#/components/schemas/LollipopJWTAuthorization"
        - name: x-pagopa-lollipop-assertion-ref
          in: header
          description: The id of the assertion to retrieve
          required: true
          schema:
            $ref: "#/components/schemas/LollipopAssertionRef"
        - name: x-pagopa-lollipop-assertion-type
          in: header
          description: The assertion type (SAML / OIDC)
          required: true
          schema:
            $ref: "#/components/schemas/AssertionType"
        - name: x-pagopa-lollipop-user-id
          in: header
          description: User's fiscal code.
          required: true
          schema:
            $ref: "#/components/schemas/LollipopUserId"
        - name: x-pagopa-lollipop-public-key
          in: header
          description: User's public key
          required: true
          schema:
            $ref: "#/components/schemas/LollipopPublicKey"
        - name: signature-input
          in: header
          description: The signature input, needed to verify the `signature` header
          required: true
          schema:
            $ref: "#/components/schemas/LollipopSignatureInput"
        - name: signature
          in: header
          description: The signature of the HTTP request, signed by the client with its private key.
          required: true
          schema:
            $ref: "#/components/schemas/LollipopSignature"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignMessagePayload"
      responses:
        "200":
          description: "Success response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignMessageResponse"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: This is an example of authentication. The LC can choose their custom auth method
      in: header
      name: X-Functions-Key
  schemas:
    LollipopMethod:
      type: string
      enum:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
    LollipopOriginalURL:
      type: string
      pattern: "^https:\/\/"
    AssertionType:
      type: string
      enum:
        - SAML
        - OIDC
    LollipopAssertionRef:
      oneOf:
        - $ref: "#/components/schemas/AssertionRefSha256"
        - $ref: "#/components/schemas/AssertionRefSha384"
        - $ref: "#/components/schemas/AssertionRefSha512"
    LollipopUserId:
      type: string
      maxLength: 16
      minLength: 16
      description: The user's fiscal code, all upper case.
      pattern: >-
        ^[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]$
    LollipopPublicKey:
      type: string
      minLength: 1
      description: represents a Base64url encode of a JWK Public Key
    LollipopJWTAuthorization:
      type: string
      minLength: 1

    LollipopContentType:
      type: string
      enum:
        - application/json
        - application/octet-stream
    LollipopContentDigest:
      type: string
      pattern: "^(sha-256=:[A-Za-z0-9+/=]{44}:|sha-384=:[A-Za-z0-9+/=]{66}:|sha-512=:[A-Za-z0-9+/=]{88}:)$"

    LollipopSignatureInput:
      type: string
      pattern: "^(((sig[0-9]+)=[^,]*?)(, ?)?)+$"
    LollipopSignature:
      type: string
      pattern: "^((sig[0-9]+)=:[A-Za-z0-9+/=]*:(, ?)?)+$"

    # AssertionRef possible inputs
    AssertionRefSha256:
      type: string
      pattern: ^(sha256-[A-Za-z0-9-_=]{1,44})$
    AssertionRefSha384:
      type: string
      pattern: ^(sha384-[A-Za-z0-9-_=]{1,66})$
    AssertionRefSha512:
      type: string
      pattern: ^(sha512-[A-Za-z0-9-_=]{1,88})$

    SignMessagePayload:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    SignMessageResponse:
      type: object
      properties:
        response:
          type: string
