openapi: 3.0.1
info:
  version: 21.1.0
  title: IO API backend shared definitions
  description: |
    shared definitions for IO API backend services
servers:
  - url: https://localhost/
paths:
  /dummy:
    get:
      responses:
        '200':
          description: ok
components:
  schemas:
    SpidLevel:
      type: string
      description: A SPID level.
      x-extensible-enum:
        - https://www.spid.gov.it/SpidL1
        - https://www.spid.gov.it/SpidL2
        - https://www.spid.gov.it/SpidL3
    AssertionRefSha256:
      type: string
      pattern: ^(sha256-[A-Za-z0-9-_=]{1,44})$
    AssertionRefSha384:
      type: string
      pattern: ^(sha384-[A-Za-z0-9-_=]{1,66})$
    AssertionRefSha512:
      type: string
      pattern: ^(sha512-[A-Za-z0-9-_=]{1,88})$
    AssertionRef:
      x-one-of: true
      allOf:
        - $ref: '#/components/schemas/AssertionRefSha512'
        - $ref: '#/components/schemas/AssertionRefSha384'
        - $ref: '#/components/schemas/AssertionRefSha256'
    PathTraversalSafePathParam:
      description: >-
        A non empty string that is safe to be used in an url parameter to avoid
        path traversal attacks
      type: string
      pattern: ^[0-9a-zA-Z\-\._\/+]+$
    Timestamp:
      type: string
      format: UTCISODateFromString
      description: A date-time field in ISO-8601 format and UTC timezone.
      x-import: '@pagopa/ts-commons/lib/dates'
      example: '2018-10-13T00:00:00.000Z'
    SessionInfo:
      type: object
      title: Session info of a user
      description: Decribe a session of an authenticated user.
      properties:
        createdAt:
          $ref: '#/components/schemas/Timestamp'
        sessionToken:
          type: string
      required:
        - createdAt
        - sessionToken
    SessionsList:
      description: Contains all active sessions for an authenticated user.
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/SessionInfo'
      required:
        - sessions
