swagger: '2.0'
info:
  version: 12.7.3
  title: Authentication API
  description: Collection of endpoints to interact with user's auth session.
host: localhost
basePath: /
schemes:
  - https
security:
  - Bearer: []
paths:
  /logout:
    x-swagger-router-controller: AuthenticationController
    post:
      operationId: logout
      summary: Execute the logout
      description: Delete user's active session and tokens.
      responses:
        '200':
          description: Logout succeeded
          schema:
            $ref: '#/definitions/SuccessResponse'
          examples:
            application/json:
              message: ok
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ProblemJson'
        '401':
          description: Bearer token null or expired.
        '500':
          description: There was an error deleting user's session.
          schema:
            $ref: '#/definitions/ProblemJson'
  /user-identity:
    x-swagger-router-controller: AuthenticationController
    get:
      operationId: getUserIdentity
      summary: Get stored user's identity
      description: Returns the user's identity stored during the login phase
      responses:
        '200':
          description: Found.
          schema:
            $ref: '#/definitions/UserIdentity'
          examples:
            application/json:
              family_name: Rossi
              fiscal_code: TMMEXQ60A10Y526X
              name: Mario
              spid_email: preferred@example.com
              spid_mobile_phone: '1234567890'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ProblemJson'
        '401':
          description: Bearer token null or expired.
        '500':
          description: There was an error retrieving user's profile.
          schema:
            $ref: '#/definitions/ProblemJson'
definitions:
  ProblemJson:
    type: object
    properties:
      type:
        type: string
        format: uri
        description: |-
          An absolute URI that identifies the problem type. When dereferenced,
          it SHOULD provide human-readable documentation for the problem type
          (e.g., using HTML).
        default: about:blank
        example: https://example.com/problem/constraint-violation
      title:
        type: string
        description: |-
          A short, summary of the problem type. Written in english and readable
          for engineers (usually not suited for non technical stakeholders and
          not localized); example: Service Unavailable
      status:
        type: integer
        format: int32
        description: >-
          The HTTP status code generated by the origin server for this
          occurrence

          of the problem.
        minimum: 100
        maximum: 600
        exclusiveMaximum: true
        example: 200
      detail:
        type: string
        description: |-
          A human readable explanation specific to this occurrence of the
          problem.
        example: There was an error processing the request
      instance:
        type: string
        format: uri
        description: >-
          An absolute URI that identifies the specific occurrence of the
          problem.

          It may or may not yield further information if dereferenced.
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
  EmailAddress:
    type: string
    format: email
    example: foobar@example.com
  FiscalCode:
    type: string
    description: User's fiscal code.
    format: FiscalCode
    x-import: '@pagopa/ts-commons/lib/strings'
    example: SPNDNL80R13C555X
  SpidUserIdentity:
    type: object
    title: SPID User Identity
    description: Describes the user's profile while it's authenticated with Spid.
    properties:
      family_name:
        type: string
      fiscal_code:
        $ref: '#/definitions/FiscalCode'
      name:
        type: string
      spid_email:
        $ref: '#/definitions/EmailAddress'
      spid_mobile_phone:
        type: string
        minLength: 1
    required:
      - family_name
      - fiscal_code
      - name
      - spid_email
      - spid_mobile_phone
  CieUserIdentity:
    type: object
    title: CIE User Identity
    description: Describes the user's profile while it's authenticated with CIE.
    properties:
      family_name:
        type: string
      fiscal_code:
        $ref: '#/definitions/FiscalCode'
      name:
        type: string
      date_of_birth:
        type: string
        format: date
    required:
      - family_name
      - fiscal_code
      - name
      - date_of_birth
  UserIdentity:
    x-one-of: true
    allOf:
      - $ref: '#/definitions/SpidUserIdentity'
      - $ref: '#/definitions/CieUserIdentity'
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
