openapi: 3.0.1
info:
  title: Carta Giovani Nazionale Operator Search API
  version: 18.3.0
servers:
  - url: https://localhost/api/cgn-search/v1
security:
  - Bearer: []
paths:
  /published-product-categories:
    get:
      summary: List of published product categories
      description: |
        List of categories that have at least a published discount
      operationId: getPublishedProductCategories
      parameters:
        - name: count_new_discounts
          in: query
          description: >-
            Indicates whether categories should be enriched with new discounts
            count.
          schema:
            type: boolean
      responses:
        '200':
          description: List of categories that have at least a published discount
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PublishedProductCategoriesResult'
        '401':
          description: Login expired.
          content: {}
        '500':
          description: Service unavailable.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /count:
    get:
      summary: Count merchants and discounts to search within
      description: |
        Count merchants and discountsto search within
      operationId: count
      responses:
        '200':
          description: Count of merchants/discounts
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CountResult'
        '400':
          description: Bad request.
          content: {}
        '401':
          description: Login expired.
          content: {}
        '500':
          description: Service unavailable.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /search:
    post:
      summary: Search merchants or discounts
      description: >
        List of merchants and discounts with the token in name and/or
        description
      operationId: search
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SearchRequest'
        required: false
      responses:
        '200':
          description: List of merchants/discounts for the given query parameters
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SearchResult'
        '400':
          description: Bad request.
          content: {}
        '401':
          description: Login expired.
          content: {}
        '500':
          description: Service unavailable.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
      x-codegen-request-body-name: body
  /online-merchants:
    post:
      summary: List of online merchants
      description: |
        List of online merchants alphabetically ordered
      operationId: getOnlineMerchants
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OnlineMerchantSearchRequest'
        required: false
      responses:
        '200':
          description: List of online merchants for the given query parameters
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OnlineMerchants'
        '401':
          description: Login expired.
          content: {}
        '500':
          description: Service unavailable.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
      x-codegen-request-body-name: body
  /offline-merchants:
    post:
      summary: List of merchants with a physical address
      description: >
        List of merchants with physical address, ordered by distance from the
        user by default
      operationId: getOfflineMerchants
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OfflineMerchantSearchRequest'
        required: false
      responses:
        '200':
          description: List of physical merchants for the given query parameters
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OfflineMerchants'
        '401':
          description: Login expired.
          content: {}
        '500':
          description: Service unavailable.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
      x-codegen-request-body-name: body
  /merchants/{merchantId}:
    get:
      summary: Retrieve merchant details
      description: |
        Retrieve merchant details together with published discounts
      operationId: getMerchant
      parameters:
        - name: merchantId
          in: path
          description: Merchant Identifier
          required: true
          schema:
            minLength: 1
            type: string
      responses:
        '200':
          description: Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Merchant'
        '401':
          description: Login expired.
          content: {}
        '404':
          description: Operator Not Found
          content: {}
        '500':
          description: Service unavailable.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
  /discount-bucket-code/{discountId}:
    get:
      summary: Retrieve a discount bucket code
      description: |
        Retrieve a discount bucket code and burns it
      operationId: getDiscountBucketCode
      parameters:
        - name: discountId
          in: path
          description: Discount Identifier
          required: true
          schema:
            minLength: 1
            type: string
      responses:
        '200':
          description: Found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DiscountBucketCode'
        '401':
          description: Login expired.
          content: {}
        '403':
          description: Access data provided are invalid or CGN not valid
          content: {}
        '404':
          description: Bucket code Not Found
          content: {}
        '410':
          description: Endpoint no longer available
          content: {}
        '500':
          description: Service unavailable.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProblemJson'
components:
  schemas:
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: >-
            A short, summary of the problem type. Written in english and
            readable

            for engineers (usually not suited for non technical stakeholders and

            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: >-
            The HTTP status code generated by the origin server for this
            occurrence

            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 200
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
        instance:
          type: string
          format: uri
          description: >-
            An absolute URI that identifies the specific occurrence of the
            problem.

            It may or may not yield further information if dereferenced.
    Merchant:
      type: object
      required:
        - id
        - name
        - discounts
        - allNationalAddresses
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        fullName:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        websiteUrl:
          type: string
          minLength: 1
        supportType:
          $ref: '#/components/schemas/SupportType'
        supportValue:
          type: string
          minLength: 1
          default: '-'
        discountCodeType:
          $ref: '#/components/schemas/DiscountCodeType'
        imageUrl:
          type: string
          minLength: 1
        discounts:
          type: array
          items:
            $ref: '#/components/schemas/Discount'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        allNationalAddresses:
          type: boolean
    SupportType:
      type: string
      default: EMAILADDRESS
      enum:
        - WEBSITE
        - PHONENUMBER
        - EMAILADDRESS
    DiscountCodeType:
      type: string
      enum:
        - static
        - api
        - landingpage
        - bucket
    OfflineMerchants:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OfflineMerchant'
    OfflineMerchant:
      type: object
      required:
        - id
        - name
        - productCategories
        - address
        - newDiscounts
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        productCategories:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategory'
        address:
          $ref: '#/components/schemas/Address'
        distance:
          description: Distance in meters
          type: integer
          minimum: 0
        newDiscounts:
          type: boolean
        numberOfNewDiscounts:
          type: number
    OfflineMerchantSearchRequest:
      type: object
      properties:
        merchantName:
          type: string
          description: Text used for searching merchants by their name
          minLength: 1
        productCategories:
          type: array
          description: List of product categories to filter the results
          items:
            $ref: '#/components/schemas/ProductCategory'
        page:
          type: integer
          description: page of result
          default: 0
          minimum: 0
        pageSize:
          type: integer
          description: elements per page
          default: 200
          minimum: 1
        userCoordinates:
          $ref: '#/components/schemas/Coordinates'
          description: User coordinates
        boundingBox:
          $ref: '#/components/schemas/BoundingBox'
          description: search area bounding box
        ordering:
          type: string
          enum:
            - distance
            - alphabetic
          default: distance
          description: Ordering type, by distance or alphabetical
    CountResult:
      type: object
      required:
        - count
      properties:
        count:
          type: number
    SearchResult:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SearchItem'
    SearchItem:
      type: object
      required:
        - id
        - name
        - description
        - newDiscounts
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        newDiscounts:
          type: boolean
    OnlineMerchants:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OnlineMerchant'
    OnlineMerchant:
      type: object
      required:
        - id
        - name
        - productCategories
        - websiteUrl
        - discountCodeType
        - newDiscounts
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        productCategories:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategory'
        websiteUrl:
          type: string
          minLength: 1
        discountCodeType:
          $ref: '#/components/schemas/DiscountCodeType'
        newDiscounts:
          type: boolean
        numberOfNewDiscounts:
          type: number
    SearchRequest:
      type: object
      properties:
        token:
          type: string
          description: >-
            Text used for searching merchants/discounts by their name and
            description
          minLength: 3
        page:
          type: integer
          description: page of result
          default: 0
          minimum: 0
        pageSize:
          type: integer
          description: elements per page
          default: 200
          minimum: 1
    OnlineMerchantSearchRequest:
      type: object
      properties:
        merchantName:
          type: string
          description: Text used for searching merchants by their name
          minLength: 1
        productCategories:
          type: array
          description: List of product categories to filter the results
          items:
            $ref: '#/components/schemas/ProductCategory'
        page:
          type: integer
          description: page of result
          default: 0
          minimum: 0
        pageSize:
          type: integer
          description: elements per page
          default: 200
          minimum: 1
    Discount:
      type: object
      required:
        - id
        - name
        - startDate
        - endDate
        - productCategories
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        productCategories:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategory'
        discount:
          type: number
          format: double
          minimum: 1
        condition:
          type: string
          minLength: 1
        staticCode:
          type: string
          minLength: 1
        landingPageUrl:
          type: string
          minLength: 1
        landingPageReferrer:
          type: string
          minLength: 1
        discountUrl:
          type: string
          minLength: 1
          maxLength: 500
        isNew:
          type: boolean
    ProductCategory:
      type: string
      enum:
        - bankingServices
        - cultureAndEntertainment
        - health
        - home
        - jobOffers
        - learning
        - sports
        - sustainableMobility
        - telephonyAndInternet
        - travelling
    Address:
      type: object
      required:
        - full_address
      properties:
        full_address:
          type: string
          minLength: 1
        latitude:
          type: number
        longitude:
          type: number
    Coordinates:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
        longitude:
          type: number
    BoundingBox:
      type: object
      required:
        - coordinates
        - deltaLatitude
        - deltaLongitude
      properties:
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        deltaLatitude:
          type: number
          description: Bounding box delta latitude
        deltaLongitude:
          type: number
          description: Bounding box delta longitude
    DiscountBucketCode:
      type: object
      required:
        - code
      properties:
        code:
          type: string
    PublishedProductCategories:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategory'
    PublishedProductCategoriesWithNewDiscountsCount:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategoryWithNewDiscountsCount'
    PublishedProductCategoriesResult:
      x-one-of: true
      allOf:
        - $ref: '#/components/schemas/PublishedProductCategoriesWithNewDiscountsCount'
        - $ref: '#/components/schemas/PublishedProductCategories'
    ProductCategoryWithNewDiscountsCount:
      type: object
      properties:
        productCategory:
          $ref: '#/components/schemas/ProductCategory'
        newDiscounts:
          type: number
      required:
        - productCategory
        - newDiscounts
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
