swagger: '2.0'
info:
  version: 13.16.0
  title: MIT Voucher service for IO App
basePath: /api/v1/mitvoucher/auth
schemes:
  - https
security:
  - Bearer: []
paths:
  /token:
    get:
      operationId: getMitVoucherToken
      summary: Retrieve a token for Mit Voucher API integration
      description: Generate a JWT to use on every MIT Voucher remote API call
      responses:
        '200':
          description: Payload with Json Web Token
          schema:
            $ref: '#/definitions/MitVoucherToken'
        '400':
          description: Payload has bad format
        '401':
          description: Bearer token null or expired
        '403':
          description: Access data provided are invalid
        '410':
          description: Endpoint no longer available
        '500':
          description: Generic server error
        '504':
          description: Gateway Timeout
definitions:
  ProblemJson:
    type: object
    properties:
      type:
        type: string
        format: uri
        description: |-
          An absolute URI that identifies the problem type. When dereferenced,
          it SHOULD provide human-readable documentation for the problem type
          (e.g., using HTML).
        default: about:blank
        example: https://example.com/problem/constraint-violation
      title:
        type: string
        description: |-
          A short, summary of the problem type. Written in english and readable
          for engineers (usually not suited for non technical stakeholders and
          not localized); example: Service Unavailable
      status:
        type: integer
        format: int32
        description: >-
          The HTTP status code generated by the origin server for this
          occurrence

          of the problem.
        minimum: 100
        maximum: 600
        exclusiveMaximum: true
        example: 200
      detail:
        type: string
        description: |-
          A human readable explanation specific to this occurrence of the
          problem.
        example: There was an error processing the request
      instance:
        type: string
        format: uri
        description: >-
          An absolute URI that identifies the specific occurrence of the
          problem.

          It may or may not yield further information if dereferenced.
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
  MitVoucherToken:
    title: Mit Voucher Token
    description: A Json Web Token used to call Mit Voucher APIs
    type: object
    properties:
      token:
        type: string
        minLength: 1
    required:
      - token
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
