/**
 * The HTTP status code generated by the origin server for this occurrence
 * of the problem.
 */

import { WithinRangeNumber } from "../../utils/numbers";

import * as t from "io-ts";

export type HttpStatusCode = t.TypeOf<typeof HttpStatusCode>;

export const HttpStatusCode = WithinRangeNumber(100, 600);
