apiVersion: v2
name: io-functions-service-messages
description: io-functions-service-messages
type: application
version: 0.14.0
appVersion: 0.14.0
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: 'https://pagopa.github.io/aks-microservice-chart-blueprint'
