/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary A citizen's profile
  *
 * Describes the citizen's profile, mostly interesting for preferences
 * attributes.
 *
 */
class LimitedProfile {
  /**
   * Create a LimitedProfile.
   * @member {array} [preferredLanguages]
   */
  constructor() {
  }

  /**
   * Defines the metadata of LimitedProfile
   *
   * @returns {object} metadata of LimitedProfile
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'LimitedProfile',
      type: {
        name: 'Composite',
        className: 'LimitedProfile',
        modelProperties: {
          preferredLanguages: {
            required: false,
            serializedName: 'preferred_languages',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = LimitedProfile;
