/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary MessageContent
  *
 */
class MessageContent {
  /**
   * Create a MessageContent.
   * @member {string} [subject]
   * @member {string} markdown
   */
  constructor() {
  }

  /**
   * Defines the metadata of MessageContent
   *
   * @returns {object} metadata of MessageContent
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MessageContent',
      type: {
        name: 'Composite',
        className: 'MessageContent',
        modelProperties: {
          subject: {
            required: false,
            serializedName: 'subject',
            type: {
              name: 'String'
            }
          },
          markdown: {
            required: true,
            serializedName: 'markdown',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MessageContent;
