/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Default addresses for notifying the recipient of the message in case no
 * address for the related channel is set in his profile.
 *
 */
class NewMessageDefaultAddresses {
  /**
   * Create a NewMessageDefaultAddresses.
   * @member {string} [email]
   */
  constructor() {
  }

  /**
   * Defines the metadata of NewMessageDefaultAddresses
   *
   * @returns {object} metadata of NewMessageDefaultAddresses
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'NewMessageDefaultAddresses',
      type: {
        name: 'Composite',
        className: 'NewMessageDefaultAddresses',
        modelProperties: {
          email: {
            required: false,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = NewMessageDefaultAddresses;
