/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary NotificationStatus
  *
 */
class NotificationStatus {
  /**
   * Create a NotificationStatus.
   * @member {string} [email]
   */
  constructor() {
  }

  /**
   * Defines the metadata of NotificationStatus
   *
   * @returns {object} metadata of NotificationStatus
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'NotificationStatus',
      type: {
        name: 'Composite',
        className: 'NotificationStatus',
        modelProperties: {
          email: {
            required: false,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = NotificationStatus;
