/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @summary pagination
  *
 * Pagination response parameters.
 *
 */
class PaginationResponse {
  /**
   * Create a PaginationResponse.
   * @member {number} [pageSize] Number of items returned for each page.
   * @member {string} [next] Contains an URL to GET the next #<page_size>
   * results in the retrieved collection of items.
   */
  constructor() {
  }

  /**
   * Defines the metadata of PaginationResponse
   *
   * @returns {object} metadata of PaginationResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PaginationResponse',
      type: {
        name: 'Composite',
        className: 'PaginationResponse',
        modelProperties: {
          pageSize: {
            required: false,
            serializedName: 'page_size',
            constraints: {
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          next: {
            required: false,
            serializedName: 'next',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = PaginationResponse;
