on:
  workflow_call:
    inputs:
      api_name:
        type: string
        required: true

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-22.04
    environment: prod-cd
    env:
      API_NAME: ${{ inputs.api_name }}
      DOCKER_IMAGE_TAG: sha256:5b26e3b170d97deb794639a039ef52ea84602b7543454fc06ac2a00f762a6a2c
      TEMPLATE_DIR: azure-dashboard
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_CI }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: pagopa/opex-dashboard-azure-action@v1.1.2
        with:
          environment: prod
          api-name: ${{ env.API_NAME }}
          config: .opex/${{ env.API_NAME }}/env/prod/config.yaml
          client-id: ${{ secrets.AZURE_CLIENT_ID_CD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          docker-version: sha256:e4245954566cd3470e1b5527d33bb58ca132ce7493eac01be9e808fd25a11c8d
