name: Opex Dashboard api_eucovidcert

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'api_eucovidcert.yaml'
      - '.github/workflows/opex_api_eucovidcert.yml'
      - '.opex/api_eucovidcert/**'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - 'api_eucovidcert.yaml'
      - '.github/workflows/opex_api_eucovidcert.yml'
      - '.opex/api_eucovidcert/**'

env:
  CLIENT_ID: 712582b4-1e38-4329-bfd2-5cd186e82529
  TENANT_ID: 7788edaf-0346-4068-9d79-c868aed15b3d
  SUBSCRIPTION_ID: ec285037-c673-4f58-b594-d7c480da4e8b
  API_NAME: api_eucovidcert

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        environment: [prod]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      # from https://github.com/pagopa/opex-dashboard-azure-action/
      - uses: pagopa/opex-dashboard-azure-action@v1.1.2
        with:
          environment: ${{ matrix.environment }}
          api-name: ${{ env.API_NAME }}
          config: .opex/${{ env.API_NAME }}/env/${{ matrix.environment }}/config.yaml
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}
          # from https://github.com/pagopa/opex-dashboard-azure-action/pkgs/container/opex-dashboard-azure-action
          docker-version: sha256:e4245954566cd3470e1b5527d33bb58ca132ce7493eac01be9e808fd25a11c8d
