name: PR - Opex Dashboard api_fast_login

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - master
    paths:
      - 'openapi/generated/api_fast_login.yaml'
      - '.github/workflows/pr_opex_api_fast_login.yml'
      - '.github/workflows/opex_api_fast_login.yml'
      - '.opex/api_fast_login/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  plan:
    uses: ./.github/workflows/call_pr_opex_api.yml
    name: Plan changes against Production
    secrets: inherit
    with:
      api_name: api_fast_login
